import os
os.environ['APP_ENV'] = 'local'
os.environ['FLASK_ENV'] = 'development'

from app import create_app
from app.identity.models.user import User
from app.notifications.services import NotificationService

app = create_app()
with app.app_context():
    # Use an existing user with the target email (twikirizeobed@gmail.com)
    u = User.query.filter_by(email="twikirizeobed@gmail.com").first()
    if not u:
        # Optionally create one if it doesn't exist (rare case)
        u = User(
            email='twikirizeobed@gmail.com',
            username='testuser',
            password_hash='x',
            email_verified=True
        )
        # But only if it's a new, unique email – ensure no other user has it
        # (we already queried, so it's safe)
        from app.extensions import db
        db.session.add(u)
        db.session.commit()

    n = NotificationService.send(
        user_id=u.id,
        notification_type='booking_confirmed',
        title='Live Email Channel Test',
        message='This email was generated by the AFCON360 notification system via Gmail SMTP.',
        channels=['email', 'in_app'],
        link='/notifications',
        priority='high',
    )

    print('NOTIFICATION_ID:', n.id if n else None)
    print('STATUS:', n.status if n else 'NONE')
    print('RECIPIENT:', u.email)
    print('RESULT:', 'EMAIL_SENT_OK' if (n and n.status == 'delivered') else 'CHECK_STATUS')

    # --- IMAP self-verification: confirm the email actually landed in the
    # recipient mailbox (Inbox / All Mail / Spam). Requires the recipient's
    # Gmail App Password in the TWK_MAIL_PASSWORD env var.
    import imaplib
    import os as _os
    import time as _time

    subject = 'Live Email Channel Test'  # matches title passed to send()
    app_pw = _os.getenv('TWK_MAIL_PASSWORD')
    if not app_pw:
        print('IMAP_VERIFY: SKIPPED (set TWK_MAIL_PASSWORD to recipient Gmail App Password to auto-confirm receipt)')
    else:
        delivered = False
        location = None
        for _ in range(10):  # poll up to ~5s
            try:
                im = imaplib.IMAP4_SSL('imap.gmail.com')
                im.login(u.email, app_pw)
                for box in ['INBOX', '[Gmail]/All Mail', '[Gmail]/Spam']:
                    try:
                        im.select(box)
                        _, data = im.search(None, 'SUBJECT', subject)
                        if data and data[0]:
                            delivered = True
                            location = box
                            break
                    except Exception:
                        continue
                im.logout()
            except Exception as e:
                print('IMAP_VERIFY: ERROR', repr(e))
                break
            if delivered:
                break
            _time.sleep(0.5)
        if delivered:
            print(f'IMAP_VERIFY: CONFIRMED in {location} (subject="{subject}")')
        else:
            print(f'IMAP_VERIFY: NOT FOUND in mailbox after polling (subject="{subject}")')
    print('CHECK_INBOX: open', u.email, '-> search "', subject, '" (also check All Mail / Promotions tab)')