"""
Event backbone persistence models.

Five tables, each with a single clear responsibility:

``domain_events``
    The **event ledger** — the immutable record of *what happened* in the
    platform. Deliberately separate from ``notification_logs``, which record
    *how we tried to communicate it*. A failed email must never rewrite the
    fact that a payment succeeded.

``outbox_events``
    The **transactional outbox**. Written in the same DB transaction as the
    business change, then relayed to the bus by a worker. This is what removes
    the "COMMIT succeeded but publish crashed" race.

``processed_events``
    **Event-level idempotency**. One row per (consumer, event_id). Redelivery of
    an event is a no-op instead of a duplicate receipt.

``event_subscriptions``
    External partner subscriptions to event types (turns AFCON360 into a
    platform rather than an application).

``webhook_deliveries``
    Per-attempt delivery history for outbound partner webhooks, with its own
    retry/DLQ lifecycle separate from user notifications.
"""

from __future__ import annotations

import enum
from datetime import datetime, timezone

from sqlalchemy import (
    BigInteger,
    Boolean,
    CheckConstraint,
    Column,
    DateTime,
    Index,
    Integer,
    JSON,
    String,
    Text,
    UniqueConstraint,
)

from app.extensions import db
from app.models.base import BaseModel


class EventStatus(str, enum.Enum):
    """Lifecycle of an event in the ledger."""
    PENDING = "pending"          # recorded, not yet published to the bus
    PUBLISHED = "published"      # handed to the bus
    PROCESSING = "processing"    # at least one consumer is working on it
    PROCESSED = "processed"      # all registered consumers acked
    PARTIAL = "partial"          # some consumers succeeded, some dead-lettered
    FAILED = "failed"            # could not be published
    DEAD_LETTER = "dead_letter"  # exhausted retries; needs manual inspection


class OutboxStatus(str, enum.Enum):
    """Lifecycle of a row in the transactional outbox."""
    PENDING = "pending"
    PUBLISHING = "publishing"
    PUBLISHED = "published"
    FAILED = "failed"
    DEAD_LETTER = "dead_letter"


class SubscriptionStatus(str, enum.Enum):
    """Lifecycle of an external partner subscription."""
    ACTIVE = "active"
    PAUSED = "paused"
    DISABLED = "disabled"


class DomainEvent(BaseModel):
    """
    Canonical domain event — the platform's internal language.

    This is an append-only ledger. Rows are never mutated except to advance
    delivery bookkeeping (``status``, ``published_at``, ``processed_at``); the
    ``payload`` and identity columns are immutable once written.
    """

    __tablename__ = 'domain_events'
    __table_args__ = (
        UniqueConstraint('event_id', name='uq_domain_events_event_id'),
        Index('idx_domain_events_type_occurred', 'event_type', 'occurred_at'),
        Index('idx_domain_events_aggregate', 'aggregate_type', 'aggregate_id'),
        Index('idx_domain_events_correlation', 'correlation_id'),
        Index('idx_domain_events_causation', 'causation_id'),
        Index('idx_domain_events_status', 'status'),
        Index('idx_domain_events_actor', 'actor_type', 'actor_id'),
        CheckConstraint(
            "status IN ('pending','published','processing','processed',"
            "'partial','failed','dead_letter')",
            name='ck_domain_events_status',
        ),
    )

    # --- identity -----------------------------------------------------
    # Stable, globally unique, generated by the producer. This is the
    # idempotency key every consumer keys off.
    event_id = Column(String(64), nullable=False, unique=True, index=True)
    event_type = Column(String(128), nullable=False, index=True)
    # Payload schema version. Consumers branch on this instead of guessing,
    # so adding a field never breaks an old consumer.
    event_version = Column(Integer, nullable=False, default=1)

    # --- subject ------------------------------------------------------
    aggregate_type = Column(String(64), nullable=True, index=True)
    aggregate_id = Column(String(128), nullable=True, index=True)

    # --- actor (who caused it) ----------------------------------------
    actor_type = Column(String(32), nullable=True)   # user, system, admin, job
    actor_id = Column(String(128), nullable=True)

    # --- tracing ------------------------------------------------------
    correlation_id = Column(String(64), nullable=True, index=True)
    causation_id = Column(String(64), nullable=True, index=True)

    # --- body ---------------------------------------------------------
    payload = Column(JSON, nullable=False, default=dict)
    event_metadata = Column(JSON, nullable=True, default=dict)

    # --- lifecycle ----------------------------------------------------
    occurred_at = Column(
        DateTime, nullable=False, default=lambda: datetime.now(timezone.utc), index=True
    )
    published_at = Column(DateTime, nullable=True)
    processed_at = Column(DateTime, nullable=True)
    status = Column(String(16), nullable=False, default=EventStatus.PENDING.value, index=True)

    def mark_published(self) -> None:
        self.status = EventStatus.PUBLISHED.value
        self.published_at = datetime.now(timezone.utc)

    def mark_processed(self) -> None:
        self.status = EventStatus.PROCESSED.value
        self.processed_at = datetime.now(timezone.utc)

    def mark_partial(self) -> None:
        self.status = EventStatus.PARTIAL.value
        self.processed_at = datetime.now(timezone.utc)

    def mark_dead_letter(self) -> None:
        self.status = EventStatus.DEAD_LETTER.value

    def to_envelope(self):
        """Rehydrate the transport-level envelope from the ledger row."""
        from .schemas import EventEnvelope

        return EventEnvelope.from_model(self)

    def __repr__(self) -> str:
        return f'<DomainEvent {self.event_id}: {self.event_type} v{self.event_version}>'


class OutboxEvent(BaseModel):
    """
    Transactional outbox row.

    Written inside the caller's business transaction::

        BEGIN
          UPDATE payments SET status='successful'
          INSERT INTO outbox_events (...)
        COMMIT

    A relay worker then moves ``pending`` rows onto the bus. Because the insert
    shares the business transaction, the event cannot vanish if the process dies
    immediately after commit — and it is never published for a transaction that
    rolled back.
    """

    __tablename__ = 'outbox_events'
    __table_args__ = (
        UniqueConstraint('event_id', name='uq_outbox_events_event_id'),
        Index('idx_outbox_status_available', 'status', 'available_at'),
        Index('idx_outbox_event_type', 'event_type'),
        CheckConstraint(
            "status IN ('pending','publishing','published','failed','dead_letter')",
            name='ck_outbox_events_status',
        ),
    )

    event_id = Column(String(64), nullable=False, unique=True, index=True)
    event_type = Column(String(128), nullable=False, index=True)
    event_version = Column(Integer, nullable=False, default=1)

    # Full serialized envelope, so the relay never needs to re-derive anything.
    envelope = Column(JSON, nullable=False, default=dict)

    status = Column(String(16), nullable=False, default=OutboxStatus.PENDING.value, index=True)
    attempts = Column(Integer, nullable=False, default=0)
    max_attempts = Column(Integer, nullable=False, default=8)
    # Backoff gate: the relay only picks up rows whose available_at has passed.
    available_at = Column(
        DateTime, nullable=False, default=lambda: datetime.now(timezone.utc), index=True
    )
    last_error = Column(Text, nullable=True)
    published_at = Column(DateTime, nullable=True)
    # Guards against two relay workers grabbing the same row.
    locked_at = Column(DateTime, nullable=True)
    locked_by = Column(String(64), nullable=True)

    def __repr__(self) -> str:
        return f'<OutboxEvent {self.event_id}: {self.event_type} {self.status}>'


class ProcessedEvent(BaseModel):
    """
    Event-level idempotency ledger.

    One row per ``(consumer, event_id)``. Before handling an event a consumer
    inserts here; a unique-constraint violation means "already done, skip".
    This is what makes at-least-once delivery safe — a replayed or duplicated
    ``payment.successful`` cannot produce a second receipt email.
    """

    __tablename__ = 'processed_events'
    __table_args__ = (
        UniqueConstraint('consumer', 'event_id', name='uq_processed_consumer_event'),
        Index('idx_processed_events_event', 'event_id'),
        Index('idx_processed_events_consumer', 'consumer'),
    )

    consumer = Column(String(64), nullable=False, index=True)
    event_id = Column(String(64), nullable=False, index=True)
    event_type = Column(String(128), nullable=True)
    status = Column(String(16), nullable=False, default='success')
    attempts = Column(Integer, nullable=False, default=1)
    error = Column(Text, nullable=True)
    processed_at = Column(
        DateTime, nullable=False, default=lambda: datetime.now(timezone.utc)
    )

    def __repr__(self) -> str:
        return f'<ProcessedEvent {self.consumer}:{self.event_id} {self.status}>'


class EventSubscription(BaseModel):
    """
    External partner subscription to platform events.

    Distinct from ``NotificationAggregator`` (which is about *delivery
    providers*). A subscription says "partner X wants booking.confirmed and
    payment.successful delivered to this HTTPS endpoint, signed with this
    secret".
    """

    __tablename__ = 'event_subscriptions'
    __table_args__ = (
        Index('idx_event_subs_status', 'status'),
        Index('idx_event_subs_subscriber', 'subscriber'),
        CheckConstraint(
            "status IN ('active','paused','disabled')",
            name='ck_event_subscriptions_status',
        ),
    )

    subscriber = Column(String(128), nullable=False, index=True)
    description = Column(Text, nullable=True)
    # List of event types, supports trailing wildcard: ["booking.*", "payment.successful"]
    event_types = Column(JSON, nullable=False, default=list)
    endpoint = Column(String(512), nullable=False)
    # HMAC-SHA256 signing secret (encrypted at rest by the settings service).
    secret = Column(String(255), nullable=True)
    status = Column(String(16), nullable=False, default=SubscriptionStatus.ACTIVE.value)
    api_version = Column(Integer, nullable=False, default=1)
    max_attempts = Column(Integer, nullable=False, default=6)
    timeout_seconds = Column(Integer, nullable=False, default=10)
    # Circuit-breaker bookkeeping so one dead partner cannot degrade the queue.
    consecutive_failures = Column(Integer, nullable=False, default=0)
    last_success_at = Column(DateTime, nullable=True)
    last_failure_at = Column(DateTime, nullable=True)
    owner_user_id = Column(BigInteger, db.ForeignKey('users.id'), nullable=True)

    def matches(self, event_type: str) -> bool:
        """True when this subscription should receive *event_type*."""
        for pattern in (self.event_types or []):
            if pattern == '*' or pattern == event_type:
                return True
            if pattern.endswith('*') and event_type.startswith(pattern[:-1]):
                return True
        return False

    def __repr__(self) -> str:
        return f'<EventSubscription {self.subscriber} -> {self.endpoint} ({self.status})>'


class WebhookDelivery(BaseModel):
    """
    One outbound webhook delivery attempt chain.

    Partner webhooks need their own reliability model — signature, timestamp,
    delivery id, retry budget, DLQ and replay — kept separate from user-facing
    notification delivery.
    """

    __tablename__ = 'webhook_deliveries'
    __table_args__ = (
        Index('idx_webhook_deliveries_sub', 'subscription_id'),
        Index('idx_webhook_deliveries_event', 'event_id'),
        Index('idx_webhook_deliveries_status', 'status', 'next_attempt_at'),
        UniqueConstraint('subscription_id', 'event_id', name='uq_webhook_sub_event'),
    )

    subscription_id = Column(
        BigInteger, db.ForeignKey('event_subscriptions.id'), nullable=False, index=True
    )
    event_id = Column(String(64), nullable=False, index=True)
    event_type = Column(String(128), nullable=False)
    delivery_id = Column(String(64), nullable=False, unique=True, index=True)
    endpoint = Column(String(512), nullable=False)
    payload = Column(JSON, nullable=False, default=dict)

    status = Column(String(16), nullable=False, default='pending', index=True)
    attempts = Column(Integer, nullable=False, default=0)
    max_attempts = Column(Integer, nullable=False, default=6)
    next_attempt_at = Column(DateTime, nullable=True, index=True)
    response_code = Column(Integer, nullable=True)
    response_body = Column(Text, nullable=True)
    last_error = Column(Text, nullable=True)
    delivered_at = Column(DateTime, nullable=True)

    def __repr__(self) -> str:
        return f'<WebhookDelivery {self.delivery_id}: {self.event_type} {self.status}>'
