"""Add system_configs table

Revision ID: 20260706_add_system_configs_table
Revises: a976e4599bfe
Create Date: 2026-07-06 15:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20260706_configs'
down_revision = 'a976e4599bfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    
    # Check if table already exists before creating
    if not conn.dialect.has_table(conn, 'system_configs'):
        op.create_table(
            'system_configs',
            sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
            sa.Column('key', sa.String(length=100), nullable=False),
            sa.Column('value', sa.Text(), nullable=False),
            sa.Column('description', sa.Text(), nullable=True),
            sa.Column('created_by', sa.BigInteger(), nullable=True),
            sa.Column('is_deleted', sa.Boolean(), nullable=False),
            sa.Column('deleted_at', sa.DateTime(), nullable=True),
            sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
            sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
            sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('key', name='uq_system_configs_key')
        )
        with op.batch_alter_table('system_configs', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_system_configs_created_at'), ['created_at'], unique=False)
            batch_op.create_index(batch_op.f('ix_system_configs_is_deleted'), ['is_deleted'], unique=False)
            batch_op.create_index(batch_op.f('ix_system_configs_key'), ['key'], unique=False)
            batch_op.create_index(batch_op.f('ix_system_configs_updated_at'), ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_configs_updated_at'))
        batch_op.drop_index(batch_op.f('ix_system_configs_key'))
        batch_op.drop_index(batch_op.f('ix_system_configs_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_system_configs_created_at'))

    op.drop_table('system_configs')
    # ### end Alembic commands ###
