"""add_booking_commission

Revision ID: 04d05161190f
Revises: 20260718_1951
Create Date: 2026-07-19 23:30:15.145940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04d05161190f'
down_revision = '20260718_1951'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accommodation_booking_commissions',
    sa.Column('booking_id', sa.BigInteger(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('commission_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('host_payout', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('platform_fee_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('host_payout_transaction_id', sa.String(length=100), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_by', sa.BigInteger(), nullable=True),
    sa.Column('refund_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['accommodation_bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['released_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id', name='uq_commission_booking')
    )
    with op.batch_alter_table('accommodation_booking_commissions', schema=None) as batch_op:
        batch_op.create_index('idx_commission_booking', ['booking_id'], unique=False)
        batch_op.create_index('idx_commission_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_booking_commissions_booking_id'), ['booking_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_accommodation_booking_commissions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_booking_commissions_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_booking_commissions_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accommodation_booking_commissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accommodation_booking_commissions_updated_at'))
        batch_op.drop_index(batch_op.f('ix_accommodation_booking_commissions_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_accommodation_booking_commissions_created_at'))
        batch_op.drop_index(batch_op.f('ix_accommodation_booking_commissions_booking_id'))
        batch_op.drop_index('idx_commission_status')
        batch_op.drop_index('idx_commission_booking')

    op.drop_table('accommodation_booking_commissions')
    # ### end Alembic commands ###
