"""Add server_default to processing_attempts and notified columns

Revision ID: 07c931b46c36
Revises: 5661738e7748
Create Date: 2026-07-25 16:40:24.228639

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '07c931b46c36'
down_revision = '5661738e7748'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_flags_risk_score'))
        batch_op.create_index('ix_content_flags_risk_score', ['risk_score', 'status'], unique=False)

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processing_attempts', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('processing_completed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('notified', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('cleaned_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('processing_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_column('processing_metadata')
        batch_op.drop_column('cleaned_at')
        batch_op.drop_column('notified')
        batch_op.drop_column('failed_at')
        batch_op.drop_column('processing_completed_at')
        batch_op.drop_column('processing_started_at')
        batch_op.drop_column('processing_attempts')

    with op.batch_alter_table('content_flags', schema=None) as batch_op:
        batch_op.drop_index('ix_content_flags_risk_score')
        batch_op.create_index(batch_op.f('ix_content_flags_risk_score'), ['risk_score'], unique=False)

    # ### end Alembic commands ###
