"""add notification important flag

Revision ID: 0976b5335f95
Revises: 4b2da98e82a8
Create Date: 2026-08-14 17:04:22.547312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0976b5335f95'
down_revision = '4b2da98e82a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_important', sa.Boolean(), server_default='false', nullable=False))
        batch_op.create_index(batch_op.f('ix_notifications_is_important'), ['is_important'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_is_important'))
        batch_op.drop_column('is_important')

    # ### end Alembic commands ###
