"""add booking owner identity columns, required_registration_fields to booking policy, and date_of_birth/nationality to guest registrations

Revision ID: 0989dcdb672f
Revises: 5c7b672dd5e2
Create Date: 2026-08-04 23:12:31.463633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0989dcdb672f'
down_revision = '5c7b672dd5e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accommodation_bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_owner_id', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('owner_claimed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('owner_email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('claim_token_hash', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_accommodation_bookings_booking_owner_id'), ['booking_owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_bookings_claim_token_hash'), ['claim_token_hash'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['booking_owner_id'], ['id'])

    with op.batch_alter_table('accommodation_guest_registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_birth', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('nationality', sa.String(length=100), nullable=True))

    with op.batch_alter_table('accommodation_property_booking_policies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('required_registration_fields', sa.JSON(), server_default='[]', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accommodation_property_booking_policies', schema=None) as batch_op:
        batch_op.drop_column('required_registration_fields')

    with op.batch_alter_table('accommodation_guest_registrations', schema=None) as batch_op:
        batch_op.drop_column('nationality')
        batch_op.drop_column('date_of_birth')

    with op.batch_alter_table('accommodation_bookings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_accommodation_bookings_claim_token_hash'))
        batch_op.drop_index(batch_op.f('ix_accommodation_bookings_booking_owner_id'))
        batch_op.drop_column('claim_token_hash')
        batch_op.drop_column('owner_email')
        batch_op.drop_column('owner_claimed_at')
        batch_op.drop_column('booking_owner_id')

    # ### end Alembic commands ###
