"""add compliance_case_notes and compliance notification types

Revision ID: 0a82c41d6cb0
Revises: 961bd8f150b3
Create Date: 2026-08-11 11:16:41.258314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a82c41d6cb0'
down_revision = '961bd8f150b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_case_notes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("kind IN ('note', 'system')", name='ck_compliance_case_note_kind'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['compliance_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compliance_case_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compliance_case_notes_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_case_notes_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_case_notes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_case_notes_public_id'), ['public_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compliance_case_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_case_notes_public_id'))
        batch_op.drop_index(batch_op.f('ix_compliance_case_notes_created_at'))
        batch_op.drop_index(batch_op.f('ix_compliance_case_notes_case_id'))
        batch_op.drop_index(batch_op.f('ix_compliance_case_notes_author_id'))

    op.drop_table('compliance_case_notes')
    # ### end Alembic commands ###
