"""enforce inventory_block_reason_enum at DB level

Revision ID: 100e8db8a57f
Revises: 20260701a
Create Date: 2026-07-01 15:38:32.174032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '100e8db8a57f'
down_revision = '20260701a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    reason_enum = sa.Enum('MAINTENANCE', 'RENOVATION', 'SEASONAL_CLOSE', 'OWNER_BLOCK', name='inventory_block_reason_enum')
    reason_enum.create(op.get_bind(), checkfirst=True)
    
    with op.batch_alter_table('accommodation_inventory_blocks', schema=None) as batch_op:
        batch_op.alter_column('reason',
               existing_type=sa.VARCHAR(length=30),
               type_=reason_enum,
               existing_nullable=False,
               postgresql_using='reason::inventory_block_reason_enum')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accommodation_inventory_blocks', schema=None) as batch_op:
        batch_op.alter_column('reason',
               existing_type=sa.Enum('MAINTENANCE', 'RENOVATION', 'SEASONAL_CLOSE', 'OWNER_BLOCK', name='inventory_block_reason_enum'),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)

    # ### end Alembic commands ###
