"""
add structure-only property_type and listing_type check constraints

Generated by:
scripts/sync_check_constraints.py

Environment: development

Revision ID: 1788729103
Revises: f1fe91ef0ebf
Create Date: 2026-09-07 00:11:43

Source of truth:
    SQLAlchemy model metadata

Target:
    Live PostgreSQL database
"""

from alembic import op


revision = '1788729103'
down_revision = 'f1fe91ef0ebf'
branch_labels = None
depends_on = None


def upgrade():
    op.create_check_constraint('ck_listing_type_valid', 'accommodation_properties', "listing_type IN ('entire_place', 'private_room', 'shared_room')")
    op.create_check_constraint('ck_property_type_valid', 'accommodation_properties', "property_type IN ('apartment', 'house', 'villa', 'lodge', 'hostel', 'hotel', 'guesthouse', 'boutique_hotel', 'resort')")


def downgrade():
    op.drop_constraint('ck_property_type_valid', 'accommodation_properties', type_='check')
    op.drop_constraint('ck_listing_type_valid', 'accommodation_properties', type_='check')
