"""
sync managed check constraints

Generated by:
scripts/sync_check_constraints.py

Environment: development

Revision ID: 1788711780
Revises: 3a73c6e6cf29
Create Date: 2026-09-06 19:23:00

Source of truth:
    SQLAlchemy model metadata

Target:
    Live PostgreSQL database
"""

from alembic import op


revision = '1788711780'
down_revision = '3a73c6e6cf29'
branch_labels = None
depends_on = None


def upgrade():
    op.create_check_constraint('ck_accounts_single_owner', 'accounts', 'user_id IS NULL OR organisation_id IS NULL')
    op.create_check_constraint('ck_accounts_owner_type_consistent', 'accounts', "(owner_type = 'user' AND user_id IS NOT NULL AND organisation_id IS NULL) OR (owner_type = 'organisation' AND (organisation_id IS NOT NULL OR user_id IS NOT NULL)) OR (owner_type IN ('platform', 'system') AND user_id IS NOT NULL AND organisation_id IS NULL)")
    op.create_check_constraint('ck_payment_identities_single_owner', 'payment_identities', 'owner_id IS NULL OR organisation_id IS NULL')
    op.create_check_constraint('ck_payment_identities_owner_type_consistent', 'payment_identities', "(owner_type = 'user' AND owner_id IS NOT NULL AND organisation_id IS NULL) OR (owner_type = 'organisation' AND (organisation_id IS NOT NULL OR owner_id IS NOT NULL)) OR (owner_type IN ('platform', 'system') AND owner_id IS NOT NULL AND organisation_id IS NULL)")


def downgrade():
    op.drop_constraint('ck_payment_identities_owner_type_consistent', 'payment_identities', type_='check')
    op.drop_constraint('ck_payment_identities_single_owner', 'payment_identities', type_='check')
    op.drop_constraint('ck_accounts_owner_type_consistent', 'accounts', type_='check')
    op.drop_constraint('ck_accounts_single_owner', 'accounts', type_='check')
