"""
M-06 ck_pickup

Generated by:
scripts/sync_check_constraints.py

Environment: development

Revision ID: 1790097621
Revises: 1790097609
Create Date: 2026-09-22 20:20:21

Source of truth:
    SQLAlchemy model metadata

Target:
    Live PostgreSQL database
"""

from alembic import op


revision = '1790097621'
down_revision = 'aab3e38879dc'
branch_labels = None
depends_on = None


def upgrade():
    op.create_check_constraint('ck_pickup_time_sane', 'transport_bookings', "pickup_time > created_at - INTERVAL '5 minutes'")


def downgrade():
    op.drop_constraint('ck_pickup_time_sane', 'transport_bookings', type_='check')
