"""add accommodation query performance indexes

Revision ID: 18288f7196e0
Revises: 8120b21c333e
Create Date: 2026-07-24 10:17:13.257078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18288f7196e0'
down_revision = '8120b21c333e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accommodation_bookings', schema=None) as batch_op:
        batch_op.create_index('idx_booking_check_in', ['check_in'], unique=False)
        batch_op.create_index('idx_booking_check_out', ['check_out'], unique=False)
        batch_op.create_index('idx_booking_created_at', ['created_at'], unique=False)

    with op.batch_alter_table('accommodation_properties', schema=None) as batch_op:
        batch_op.create_index('idx_property_owner_status', ['owner_user_id', 'status'], unique=False)
        batch_op.create_index('idx_property_status', ['status'], unique=False)
        batch_op.create_index('idx_property_verified', ['is_verified'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accommodation_properties', schema=None) as batch_op:
        batch_op.drop_index('idx_property_verified')
        batch_op.drop_index('idx_property_status')
        batch_op.drop_index('idx_property_owner_status')

    with op.batch_alter_table('accommodation_bookings', schema=None) as batch_op:
        batch_op.drop_index('idx_booking_created_at')
        batch_op.drop_index('idx_booking_check_out')
        batch_op.drop_index('idx_booking_check_in')

    # ### end Alembic commands ###
