"""Add missing foreign keys to transport models

Revision ID: 1cf185297670
Revises: a843f5c5ecb8
Create Date: 2026-02-14 17:43:43.311810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cf185297670'
down_revision = 'a843f5c5ecb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transport_bookings', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'transport_vehicles', ['assigned_vehicle_id'], ['id'])
        batch_op.create_foreign_key(None, 'driver_profiles', ['assigned_driver_id'], ['id'])
        batch_op.create_foreign_key(None, 'transport_scheduled_routes', ['assigned_route_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('transport_incidents', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'transport_vehicles', ['vehicle_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'driver_profiles', ['driver_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'transport_bookings', ['booking_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('transport_ratings', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'transport_bookings', ['booking_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('transport_scheduled_routes', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'transport_vehicles', ['current_vehicle_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'driver_profiles', ['current_driver_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transport_scheduled_routes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('transport_ratings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('transport_incidents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('transport_bookings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
