"""Add DEFAULT NOW() to audit_logs.created_at

Revision ID: 20260410_audit_logs_fix_created_at
Revises:
Create Date: 2026-04-10 22:13:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20260410_audit_logs_fix_created_at'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # For PostgreSQL
    op.execute("ALTER TABLE audit_logs ALTER COLUMN created_at SET DEFAULT NOW()")
    # For SQLite compatibility, also handle with batch operation
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE audit_logs ALTER COLUMN created_at DROP DEFAULT")
    # ### end Alembic commands ###
