"""add organizer_profiles table

Revision ID: 23a2748dc5d1
Revises: 8a0deccce6f6
Create Date: 2026-08-21 15:36:44.893316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23a2748dc5d1'
down_revision = '8a0deccce6f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizer_profiles',
    sa.Column('public_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('account_verified', sa.Boolean(), nullable=False),
    sa.Column('kyc_tier', sa.Integer(), nullable=True),
    sa.Column('attended_events_count', sa.Integer(), nullable=False),
    sa.Column('total_registrations', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('eligibility_passed', sa.Boolean(), nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('organization_name', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'public_id', name='uq_organizer_profile_user_pub')
    )
    with op.batch_alter_table('organizer_profiles', schema=None) as batch_op:
        batch_op.create_index('idx_organizer_profile_status', ['status'], unique=False)
        batch_op.create_index('idx_organizer_profile_user', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organizer_profiles_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_organizer_profiles_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_organizer_profiles_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_organizer_profiles_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_organizer_profiles_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizer_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizer_profiles_updated_at'))
        batch_op.drop_index(batch_op.f('ix_organizer_profiles_status'))
        batch_op.drop_index(batch_op.f('ix_organizer_profiles_public_id'))
        batch_op.drop_index(batch_op.f('ix_organizer_profiles_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_organizer_profiles_created_at'))
        batch_op.drop_index('idx_organizer_profile_user')
        batch_op.drop_index('idx_organizer_profile_status')

    op.drop_table('organizer_profiles')
    # ### end Alembic commands ###
