"""add email_verified_at and phone_verified_at to users

Revision ID: 2499ed67dc8c
Revises: a7c3e91b4d28
Create Date: 2026-08-08 18:56:56.297032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2499ed67dc8c'
down_revision = 'a7c3e91b4d28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_configurations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_channels', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('email_verification_required_for', sa.JSON(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('phone_verified_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('activated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('activated_at')
        batch_op.drop_column('phone_verified_at')
        batch_op.drop_column('email_verified_at')

    with op.batch_alter_table('auth_configurations', schema=None) as batch_op:
        batch_op.drop_column('email_verification_required_for')
        batch_op.drop_column('otp_channels')

    # ### end Alembic commands ###
