"""add_host_profiles_property_documents_reviews

Revision ID: 2d264b2fdc99
Revises: 04d05161190f
Create Date: 2026-07-20 00:32:35.842986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d264b2fdc99'
down_revision = '04d05161190f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accommodation_host_org_profiles',
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.Column('is_active_host', sa.Boolean(), nullable=False),
    sa.Column('is_suspended', sa.Boolean(), nullable=False),
    sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suspended_reason', sa.String(length=500), nullable=True),
    sa.Column('suspended_by', sa.BigInteger(), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('onboarding_step', sa.String(length=50), nullable=False),
    sa.Column('default_payout_method', sa.String(length=50), nullable=False),
    sa.Column('payout_account_details', sa.JSON(), nullable=True),
    sa.Column('commission_override_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tax_id', sa.String(length=128), nullable=True),
    sa.Column('tax_country', sa.String(length=2), nullable=True),
    sa.Column('vat_number', sa.String(length=64), nullable=True),
    sa.Column('business_registration_no', sa.String(length=128), nullable=True),
    sa.Column('total_listings', sa.BigInteger(), nullable=False),
    sa.Column('active_listings', sa.BigInteger(), nullable=False),
    sa.Column('total_bookings', sa.BigInteger(), nullable=False),
    sa.Column('total_reviews', sa.BigInteger(), nullable=False),
    sa.Column('avg_rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('total_earnings', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pending_payout', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['suspended_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', name='uq_host_org_profile_org')
    )
    with op.batch_alter_table('accommodation_host_org_profiles', schema=None) as batch_op:
        batch_op.create_index('idx_host_org_profile_active', ['is_active_host'], unique=False)
        batch_op.create_index('idx_host_org_profile_org', ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_host_org_profiles_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_host_org_profiles_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_host_org_profiles_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_host_org_profiles_tax_id'), ['tax_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_host_org_profiles_updated_at'), ['updated_at'], unique=False)

    op.create_table('accommodation_host_profiles',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('is_active_host', sa.Boolean(), nullable=False),
    sa.Column('is_suspended', sa.Boolean(), nullable=False),
    sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suspended_reason', sa.String(length=500), nullable=True),
    sa.Column('suspended_by', sa.BigInteger(), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('onboarding_step', sa.String(length=50), nullable=False),
    sa.Column('default_payout_method', sa.String(length=50), nullable=False),
    sa.Column('commission_override_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tax_id', sa.String(length=128), nullable=True),
    sa.Column('tax_country', sa.String(length=2), nullable=True),
    sa.Column('vat_number', sa.String(length=64), nullable=True),
    sa.Column('total_listings', sa.BigInteger(), nullable=False),
    sa.Column('active_listings', sa.BigInteger(), nullable=False),
    sa.Column('total_bookings', sa.BigInteger(), nullable=False),
    sa.Column('total_reviews', sa.BigInteger(), nullable=False),
    sa.Column('avg_rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('total_earnings', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pending_payout', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['suspended_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_host_profile_user')
    )
    with op.batch_alter_table('accommodation_host_profiles', schema=None) as batch_op:
        batch_op.create_index('idx_host_profile_active', ['is_active_host'], unique=False)
        batch_op.create_index('idx_host_profile_user', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_host_profiles_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_host_profiles_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_host_profiles_tax_id'), ['tax_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_host_profiles_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_host_profiles_user_id'), ['user_id'], unique=False)

    op.create_table('accommodation_property_documents',
    sa.Column('property_id', sa.BigInteger(), nullable=True),
    sa.Column('host_user_id', sa.BigInteger(), nullable=True),
    sa.Column('document_type', sa.Enum('ID_DOCUMENT', 'BUSINESS_LICENSE', 'TAX_CERTIFICATE', 'PROPERTY_DEED', 'INSURANCE_CERTIFICATE', 'OTHER', name='propertydocumenttype'), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED', name='propertydocumentstatus'), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.BigInteger(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['host_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['accommodation_properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accommodation_property_documents', schema=None) as batch_op:
        batch_op.create_index('idx_property_document_host', ['host_user_id'], unique=False)
        batch_op.create_index('idx_property_document_property', ['property_id'], unique=False)
        batch_op.create_index('idx_property_document_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_property_documents_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_property_documents_document_type'), ['document_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_property_documents_host_user_id'), ['host_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_property_documents_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_property_documents_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_property_documents_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_property_documents_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accommodation_property_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accommodation_property_documents_updated_at'))
        batch_op.drop_index(batch_op.f('ix_accommodation_property_documents_status'))
        batch_op.drop_index(batch_op.f('ix_accommodation_property_documents_property_id'))
        batch_op.drop_index(batch_op.f('ix_accommodation_property_documents_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_accommodation_property_documents_host_user_id'))
        batch_op.drop_index(batch_op.f('ix_accommodation_property_documents_document_type'))
        batch_op.drop_index(batch_op.f('ix_accommodation_property_documents_created_at'))
        batch_op.drop_index('idx_property_document_status')
        batch_op.drop_index('idx_property_document_property')
        batch_op.drop_index('idx_property_document_host')

    op.drop_table('accommodation_property_documents')
    with op.batch_alter_table('accommodation_host_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accommodation_host_profiles_user_id'))
        batch_op.drop_index(batch_op.f('ix_accommodation_host_profiles_updated_at'))
        batch_op.drop_index(batch_op.f('ix_accommodation_host_profiles_tax_id'))
        batch_op.drop_index(batch_op.f('ix_accommodation_host_profiles_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_accommodation_host_profiles_created_at'))
        batch_op.drop_index('idx_host_profile_user')
        batch_op.drop_index('idx_host_profile_active')

    op.drop_table('accommodation_host_profiles')
    with op.batch_alter_table('accommodation_host_org_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accommodation_host_org_profiles_updated_at'))
        batch_op.drop_index(batch_op.f('ix_accommodation_host_org_profiles_tax_id'))
        batch_op.drop_index(batch_op.f('ix_accommodation_host_org_profiles_org_id'))
        batch_op.drop_index(batch_op.f('ix_accommodation_host_org_profiles_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_accommodation_host_org_profiles_created_at'))
        batch_op.drop_index('idx_host_org_profile_org')
        batch_op.drop_index('idx_host_org_profile_active')

    op.drop_table('accommodation_host_org_profiles')
    # ### end Alembic commands ###
