"""add accommodation_booking_payments

Revision ID: 31eef7f1f4a2
Revises: 88d91ff49abe
Create Date: 2026-07-28 17:26:34.711990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31eef7f1f4a2'
down_revision = '88d91ff49abe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_nonces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_nonces_nonce'))
        batch_op.create_index('ix_user_nonces_nonce', ['nonce'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_nonces', schema=None) as batch_op:
        batch_op.drop_index('ix_user_nonces_nonce')
        batch_op.create_index(batch_op.f('ix_user_nonces_nonce'), ['nonce'], unique=True)

    # ### end Alembic commands ###
