"""Add foreign keys and history tracking

Revision ID: 338232b080ca
Revises: b70990c4bbd1
Create Date: 2026-02-14 15:02:43.479888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '338232b080ca'
down_revision = 'b70990c4bbd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('driver_profiles', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('organisation_transport_profiles', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'organisations', ['organisation_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organisation_transport_profiles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('driver_profiles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
