"""Add accommodation room holds, guest registrations, hold type columns, and booking deadline columns

Revision ID: 3395bb381c6a
Revises: 8045e2548d4b
Create Date: 2026-08-01 13:10:29.891093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3395bb381c6a'
down_revision = '8045e2548d4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accommodation_guest_registrations',
    sa.Column('booking_id', sa.BigInteger(), nullable=False),
    sa.Column('guest_user_id', sa.BigInteger(), nullable=True),
    sa.Column('guest_name', sa.String(length=255), nullable=False),
    sa.Column('guest_email', sa.String(length=255), nullable=True),
    sa.Column('guest_phone', sa.String(length=50), nullable=True),
    sa.Column('relationship_type', sa.String(length=30), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('id_document_type', sa.String(length=30), nullable=True),
    sa.Column('id_document_number', sa.String(length=100), nullable=True),
    sa.Column('id_document_url', sa.String(length=500), nullable=True),
    sa.Column('id_document_expiry', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.BigInteger(), nullable=True),
    sa.Column('host_override', sa.Boolean(), nullable=False),
    sa.Column('host_override_reason', sa.Text(), nullable=True),
    sa.Column('host_override_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('host_override_by', sa.BigInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('registration_source', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'in_progress', 'completed', 'skipped')", name='ck_guest_reg_status_valid'),
    sa.ForeignKeyConstraint(['booking_id'], ['accommodation_bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guest_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['host_override_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id', 'guest_user_id', name='uq_booking_guest')
    )
    with op.batch_alter_table('accommodation_guest_registrations', schema=None) as batch_op:
        batch_op.create_index('idx_guest_reg_booking', ['booking_id'], unique=False)
        batch_op.create_index('idx_guest_reg_status', ['status'], unique=False)
        batch_op.create_index('idx_guest_reg_user', ['guest_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_guest_registrations_booking_id'), ['booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_guest_registrations_guest_user_id'), ['guest_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_guest_registrations_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_guest_registrations_status'), ['status'], unique=False)

    with op.batch_alter_table('accommodation_bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hold_expires_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('approval_deadline', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('registration_deadline', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_accommodation_bookings_approval_deadline'), ['approval_deadline'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_bookings_hold_expires_at'), ['hold_expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_bookings_registration_deadline'), ['registration_deadline'], unique=False)

    with op.batch_alter_table('accommodation_room_holds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hold_type', sa.String(length=30), server_default='payment', nullable=False))
        batch_op.add_column(sa.Column('approval_sla_hours', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_accommodation_room_holds_hold_type'), ['hold_type'], unique=False)

    with op.batch_alter_table('accommodation_rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
        batch_op.create_index(batch_op.f('ix_accommodation_rooms_is_active'), ['is_active'], unique=False)

    with op.batch_alter_table('content_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_flags_risk_score'))
        batch_op.create_index(batch_op.f('ix_content_flags_risk_score'), ['risk_score'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_flags_risk_score'))
        batch_op.create_index(batch_op.f('ix_content_flags_risk_score'), ['risk_score', 'status'], unique=False)

    with op.batch_alter_table('accommodation_rooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accommodation_rooms_is_active'))
        batch_op.drop_column('is_active')

    with op.batch_alter_table('accommodation_room_holds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accommodation_room_holds_hold_type'))
        batch_op.drop_column('approval_sla_hours')
        batch_op.drop_column('hold_type')

    with op.batch_alter_table('accommodation_bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accommodation_bookings_registration_deadline'))
        batch_op.drop_index(batch_op.f('ix_accommodation_bookings_hold_expires_at'))
        batch_op.drop_index(batch_op.f('ix_accommodation_bookings_approval_deadline'))
        batch_op.drop_column('registration_deadline')
        batch_op.drop_column('approval_deadline')
        batch_op.drop_column('hold_expires_at')

    with op.batch_alter_table('accommodation_guest_registrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accommodation_guest_registrations_status'))
        batch_op.drop_index(batch_op.f('ix_accommodation_guest_registrations_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_accommodation_guest_registrations_guest_user_id'))
        batch_op.drop_index(batch_op.f('ix_accommodation_guest_registrations_booking_id'))
        batch_op.drop_index('idx_guest_reg_user')
        batch_op.drop_index('idx_guest_reg_status')
        batch_op.drop_index('idx_guest_reg_booking')

    op.drop_table('accommodation_guest_registrations')
    # ### end Alembic commands ###
