"""add verification level, security deposit to bookings and policy

Revision ID: 396efe6667ff
Revises: ec7e4f84cf90
Create Date: 2026-08-02 20:43:14.833183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '396efe6667ff'
down_revision = 'ec7e4f84cf90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accommodation_property_booking_policies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_level', sa.String(length=30), server_default='none', nullable=False))
        batch_op.add_column(sa.Column('require_security_deposit', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('security_deposit_amount', sa.Numeric(precision=10, scale=2), server_default='0', nullable=True))

    with op.batch_alter_table('content_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_flags_risk_score'))
        batch_op.create_index(batch_op.f('ix_content_flags_risk_score'), ['risk_score'], unique=False)

    with op.batch_alter_table('user_nonces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_nonces_nonce'))
        batch_op.create_index('ix_user_nonces_nonce', ['nonce'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_nonces', schema=None) as batch_op:
        batch_op.drop_index('ix_user_nonces_nonce')
        batch_op.create_index(batch_op.f('ix_user_nonces_nonce'), ['nonce'], unique=True)

    with op.batch_alter_table('content_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_flags_risk_score'))
        batch_op.create_index(batch_op.f('ix_content_flags_risk_score'), ['risk_score', 'status'], unique=False)

    with op.batch_alter_table('accommodation_property_booking_policies', schema=None) as batch_op:
        batch_op.drop_column('security_deposit_amount')
        batch_op.drop_column('require_security_deposit')
        batch_op.drop_column('verification_level')

    # ### end Alembic commands ###
