"""add provider_participations universal provider participation registry

Revision ID: 3a73c6e6cf29
Revises: 9f75675b5e52
Create Date: 2026-09-05 14:21:58.378253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a73c6e6cf29'
down_revision = '9f75675b5e52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_participations',
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('organisation_id', sa.BigInteger(), nullable=True),
    sa.Column('capability_code', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("capability_code IN ('accommodation','transport','events','tourism','venue')", name='ck_provider_participations_capability_code'),
    sa.CheckConstraint("status IN ('intent','activated','suspended','revoked','deactivated')", name='ck_provider_participations_status'),
    sa.CheckConstraint('((user_id IS NOT NULL AND organisation_id IS NULL) OR (user_id IS NULL AND organisation_id IS NOT NULL))', name='ck_provider_participations_single_subject'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisation_id', 'capability_code', name='uq_provider_participation_org_code'),
    sa.UniqueConstraint('user_id', 'capability_code', name='uq_provider_participation_user_code')
    )
    with op.batch_alter_table('provider_participations', schema=None) as batch_op:
        batch_op.create_index('ix_provider_participation_code_status', ['capability_code', 'status'], unique=False)
        batch_op.create_index('ix_provider_participation_org_deleted', ['organisation_id', 'is_deleted'], unique=False)
        batch_op.create_index('ix_provider_participation_user_deleted', ['user_id', 'is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_participations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_participations_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_participations_organisation_id'), ['organisation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_participations_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_participations_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provider_participations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_participations_user_id'))
        batch_op.drop_index(batch_op.f('ix_provider_participations_updated_at'))
        batch_op.drop_index(batch_op.f('ix_provider_participations_organisation_id'))
        batch_op.drop_index(batch_op.f('ix_provider_participations_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_provider_participations_created_at'))
        batch_op.drop_index('ix_provider_participation_user_deleted')
        batch_op.drop_index('ix_provider_participation_org_deleted')
        batch_op.drop_index('ix_provider_participation_code_status')

    op.drop_table('provider_participations')
    # ### end Alembic commands ###
