"""organisation classification catalogues

Revision ID: 43a863fe3531
Revises: 5e80dc4ac345
Create Date: 2026-09-15 14:03:07.272272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43a863fe3531'
down_revision = '5e80dc4ac345'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisation_categories',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_organisation_category_code')
    )
    with op.batch_alter_table('organisation_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organisation_categories_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_organisation_categories_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_organisation_categories_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_organisation_categories_updated_at'), ['updated_at'], unique=False)

    op.create_table('organisation_types',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('category_code', sa.String(length=50), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_code'], ['organisation_categories.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_organisation_type_code')
    )
    with op.batch_alter_table('organisation_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organisation_types_category_code'), ['category_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_organisation_types_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_organisation_types_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_organisation_types_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_organisation_types_updated_at'), ['updated_at'], unique=False)

    with op.batch_alter_table('organisations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organisation_type_code', sa.String(length=40), nullable=True))
        batch_op.create_index(batch_op.f('ix_organisations_organisation_type_code'), ['organisation_type_code'], unique=False)
        batch_op.create_foreign_key(None, 'organisation_types', ['organisation_type_code'], ['code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organisations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_organisations_organisation_type_code'))
        batch_op.drop_column('organisation_type_code')

    with op.batch_alter_table('organisation_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organisation_types_updated_at'))
        batch_op.drop_index(batch_op.f('ix_organisation_types_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_organisation_types_created_at'))
        batch_op.drop_index(batch_op.f('ix_organisation_types_code'))
        batch_op.drop_index(batch_op.f('ix_organisation_types_category_code'))

    op.drop_table('organisation_types')
    with op.batch_alter_table('organisation_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organisation_categories_updated_at'))
        batch_op.drop_index(batch_op.f('ix_organisation_categories_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_organisation_categories_created_at'))
        batch_op.drop_index(batch_op.f('ix_organisation_categories_code'))

    op.drop_table('organisation_categories')
    # ### end Alembic commands ###
