"""add event_assignments table

Revision ID: 489d61e4ca9b
Revises: dce3342ee153
Create Date: 2026-04-22 23:30:07.762483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '489d61e4ca9b'
down_revision = 'dce3342ee153'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_assignments',
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('attendee_id', sa.BigInteger(), nullable=True),
    sa.Column('registration_id', sa.BigInteger(), nullable=True),
    sa.Column('assignment_type', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('assigned_by_id', sa.BigInteger(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['attendee_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registration_id'], ['event_registrations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'attendee_id', name='uq_event_assignment')
    )
    with op.batch_alter_table('event_assignments', schema=None) as batch_op:
        batch_op.create_index('idx_event_assignment_attendee', ['attendee_id'], unique=False)
        batch_op.create_index('idx_event_assignment_event', ['event_id'], unique=False)
        batch_op.create_index('idx_event_assignment_registration', ['registration_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_assignments_attendee_id'), ['attendee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_assignments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_assignments_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_assignments_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_assignments_updated_at'))
        batch_op.drop_index(batch_op.f('ix_event_assignments_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_event_assignments_created_at'))
        batch_op.drop_index(batch_op.f('ix_event_assignments_attendee_id'))
        batch_op.drop_index('idx_event_assignment_registration')
        batch_op.drop_index('idx_event_assignment_event')
        batch_op.drop_index('idx_event_assignment_attendee')

    op.drop_table('event_assignments')
    # ### end Alembic commands ###
