"""add_agents_enabled_to_wallet_config

Revision ID: 5582ce532c6f
Revises: 2459945a58a4
Create Date: 2026-06-17 09:40:30.851118

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5582ce532c6f'
down_revision = '2459945a58a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_method_configs',
    sa.Column('method_id', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('method_type', sa.String(length=50), nullable=False),
    sa.Column('provider_name', sa.String(length=50), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('requires_phone', sa.Boolean(), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=True),
    sa.Column('api_secret', sa.String(length=255), nullable=True),
    sa.Column('sandbox_url', sa.String(length=255), nullable=True),
    sa.Column('production_url', sa.String(length=255), nullable=True),
    sa.Column('use_sandbox', sa.Boolean(), nullable=False),
    sa.Column('supported_currencies', sa.JSON(), nullable=True),
    sa.Column('min_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('transaction_fee', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('last_tested_at', sa.DateTime(), nullable=True),
    sa.Column('last_test_result', sa.String(length=20), nullable=True),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_method_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_method_configs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_method_configs_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_method_configs_method_id'), ['method_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_payment_method_configs_updated_at'), ['updated_at'], unique=False)

    op.create_table('payment_provider_configs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('provider_name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('is_sandbox', sa.Boolean(), nullable=False),
    sa.Column('secret_key', sa.Text(), nullable=True),
    sa.Column('public_key', sa.Text(), nullable=True),
    sa.Column('encryption_key', sa.Text(), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('webhook_url', sa.String(length=255), nullable=True),
    sa.Column('webhook_secret', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('last_tested_at', sa.DateTime(), nullable=True),
    sa.Column('last_test_result', sa.String(length=20), nullable=True),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_provider_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_provider_configs_provider_name'), ['provider_name'], unique=True)

    op.create_table('wallet_system_configs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('deposits_enabled', sa.Boolean(), nullable=False),
    sa.Column('withdrawals_enabled', sa.Boolean(), nullable=False),
    sa.Column('transfers_enabled', sa.Boolean(), nullable=False),
    sa.Column('fx_enabled', sa.Boolean(), nullable=False),
    sa.Column('agents_enabled', sa.Boolean(), nullable=False),
    sa.Column('max_deposit_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('max_withdrawal_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('max_transfer_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('deposit_fee_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('withdrawal_fee_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('transfer_fee_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fx_spread_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('notify_large_transactions', sa.Boolean(), nullable=True),
    sa.Column('large_transaction_threshold', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('require_kyc_for_deposits', sa.Boolean(), nullable=True),
    sa.Column('require_kyc_for_withdrawals', sa.Boolean(), nullable=True),
    sa.Column('require_kyc_for_transfers', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_payment_preferences',
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('accepted_methods', sa.JSON(), nullable=True),
    sa.Column('preferred_currency', sa.String(length=3), nullable=False),
    sa.Column('auto_convert_wallet', sa.Boolean(), nullable=False),
    sa.Column('wallet_conversion_rate', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('payment_settings', sa.JSON(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_payment_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_payment_preferences_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_payment_preferences_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_payment_preferences_updated_at'), ['updated_at'], unique=False)

    with op.batch_alter_table('fan_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_fan_profiles_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_fan_profiles_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_fan_profiles_updated_at'), ['updated_at'], unique=False)

    with op.batch_alter_table('user_dashboard_contexts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
        batch_op.create_index(batch_op.f('ix_user_dashboard_contexts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_dashboard_contexts_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_dashboard_contexts_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_dashboard_contexts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_dashboard_contexts_updated_at'))
        batch_op.drop_index(batch_op.f('ix_user_dashboard_contexts_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_user_dashboard_contexts_created_at'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('fan_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fan_profiles_updated_at'))
        batch_op.drop_index(batch_op.f('ix_fan_profiles_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_fan_profiles_created_at'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('event_payment_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_payment_preferences_updated_at'))
        batch_op.drop_index(batch_op.f('ix_event_payment_preferences_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_event_payment_preferences_created_at'))

    op.drop_table('event_payment_preferences')
    op.drop_table('wallet_system_configs')
    with op.batch_alter_table('payment_provider_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_provider_configs_provider_name'))

    op.drop_table('payment_provider_configs')
    with op.batch_alter_table('payment_method_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_method_configs_updated_at'))
        batch_op.drop_index(batch_op.f('ix_payment_method_configs_method_id'))
        batch_op.drop_index(batch_op.f('ix_payment_method_configs_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_payment_method_configs_created_at'))

    op.drop_table('payment_method_configs')
    # ### end Alembic commands ###
