"""Add compliance models and integration fields

Revision ID: 56cf92e4fdef
Revises: 1e93a437d0e6
Create Date: 2026-04-29 21:11:07.076956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56cf92e4fdef'
down_revision = '1e93a437d0e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('case_type', sa.Enum('KYC_REVIEW', 'KYB_REVIEW', 'AML_ALERT', 'PAYOUT_REVIEW', 'DATA_REQUEST', 'FLAG_ESCALATION', 'LICENSE_REVIEW', 'OTHER', name='compliancecasetype'), nullable=False),
    sa.Column('case_number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_REVIEW', 'PENDING_INFO', 'APPROVED', 'REJECTED', 'ESCALATED', 'CLOSED', name='compliancecasestatus'), nullable=False),
    sa.Column('priority', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='compliancecasepriority'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.Column('kyc_id', sa.Integer(), nullable=True),
    sa.Column('payout_id', sa.Integer(), nullable=True),
    sa.Column('flag_id', sa.Integer(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('escalated_from', sa.Integer(), nullable=True),
    sa.Column('escalated_at', sa.DateTime(), nullable=True),
    sa.Column('escalation_reason', sa.Text(), nullable=True),
    sa.Column('sla_due_at', sa.DateTime(), nullable=True),
    sa.Column('sla_priority', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='compliancecasepriority'), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compliance_cases', schema=None) as batch_op:
        batch_op.create_index('idx_case_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_case_sla_due', ['sla_due_at'], unique=False)
        batch_op.create_index('idx_case_status_priority', ['status', 'priority'], unique=False)
        batch_op.create_index('idx_case_type_status', ['case_type', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_cases_assigned_to'), ['assigned_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_cases_case_number'), ['case_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_compliance_cases_case_type'), ['case_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_cases_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_cases_flag_id'), ['flag_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_cases_kyc_id'), ['kyc_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_cases_organisation_id'), ['organisation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_cases_payout_id'), ['payout_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_cases_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_cases_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_compliance_cases_sla_due_at'), ['sla_due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_cases_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_cases_user_id'), ['user_id'], unique=False)

    op.create_table('compliance_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('report_number', sa.String(length=50), nullable=False),
    sa.Column('report_type', sa.Enum('KYC_SUMMARY', 'AML_SUMMARY', 'PAYOUT_SUMMARY', 'CASE_HISTORY', 'AUDIT_TRAIL', 'RISK_ASSESSMENT', 'REGULATORY_FILING', name='compliancereporttype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parameters', sa.Text(), nullable=True),
    sa.Column('date_range_start', sa.DateTime(), nullable=True),
    sa.Column('date_range_end', sa.DateTime(), nullable=True),
    sa.Column('report_data', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_format', sa.String(length=20), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('distributed_to', sa.Text(), nullable=True),
    sa.Column('distributed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compliance_reports', schema=None) as batch_op:
        batch_op.create_index('idx_report_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_report_date_range', ['date_range_start', 'date_range_end'], unique=False)
        batch_op.create_index('idx_report_type_status', ['report_type', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_reports_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_reports_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_compliance_reports_report_number'), ['report_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_compliance_reports_report_type'), ['report_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_reports_status'), ['status'], unique=False)

    op.create_table('data_subject_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('request_number', sa.String(length=50), nullable=False),
    sa.Column('request_type', sa.Enum('ACCESS', 'DELETION', 'RECTIFICATION', 'PORTABILITY', 'OBJECTION', name='datasubjectrequesttype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'VERIFIED', 'PROCESSING', 'COMPLETED', 'REJECTED', 'EXPIRED', name='datasubjectrequeststatus'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('requester_email', sa.String(length=255), nullable=False),
    sa.Column('requester_name', sa.String(length=255), nullable=False),
    sa.Column('request_details', sa.Text(), nullable=False),
    sa.Column('data_categories', sa.Text(), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('identity_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_method', sa.String(length=100), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('response_data', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('legal_basis', sa.String(length=255), nullable=True),
    sa.Column('exemption_applied', sa.Boolean(), nullable=True),
    sa.Column('exemption_reason', sa.Text(), nullable=True),
    sa.Column('sla_due_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_subject_requests', schema=None) as batch_op:
        batch_op.create_index('idx_dsr_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_dsr_sla_due', ['sla_due_at'], unique=False)
        batch_op.create_index('idx_dsr_type_status', ['request_type', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_subject_requests_assigned_to'), ['assigned_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_subject_requests_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_subject_requests_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_data_subject_requests_request_number'), ['request_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_data_subject_requests_request_type'), ['request_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_subject_requests_sla_due_at'), ['sla_due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_subject_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_subject_requests_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('content_flags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compliance_case_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('referred_to_compliance', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('referred_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('referred_by', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_content_flags_compliance_case_id'), ['compliance_case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_flags_referred_to_compliance'), ['referred_to_compliance'], unique=False)
        batch_op.create_foreign_key(None, 'compliance_cases', ['compliance_case_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['referred_by'], ['id'])

    with op.batch_alter_table('kyc_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compliance_case_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('compliance_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('compliance_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('compliance_reviewed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('compliance_reviewed_by', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('referred_to_compliance', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('referred_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('referred_by', sa.BigInteger(), nullable=True))
        batch_op.create_index(batch_op.f('ix_kyc_records_compliance_case_id'), ['compliance_case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kyc_records_compliance_status'), ['compliance_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_kyc_records_referred_to_compliance'), ['referred_to_compliance'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['referred_by'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['compliance_reviewed_by'], ['id'])
        batch_op.create_foreign_key(None, 'compliance_cases', ['compliance_case_id'], ['id'])

    with op.batch_alter_table('organisations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compliance_case_id', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('compliance_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('compliance_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('compliance_reviewed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('compliance_reviewed_by', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('referred_to_compliance', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('referred_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('referred_by', sa.BigInteger(), nullable=True))
        batch_op.create_index(batch_op.f('ix_organisations_compliance_case_id'), ['compliance_case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organisations_compliance_status'), ['compliance_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_organisations_referred_to_compliance'), ['referred_to_compliance'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['referred_by'], ['id'])
        batch_op.create_foreign_key(None, 'compliance_cases', ['compliance_case_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['compliance_reviewed_by'], ['id'])

    with op.batch_alter_table('payout_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compliance_case_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('compliance_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('compliance_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('compliance_reviewed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('compliance_reviewed_by', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('referred_to_compliance', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('referred_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('referred_by', sa.BigInteger(), nullable=True))
        batch_op.create_index(batch_op.f('ix_payout_requests_compliance_case_id'), ['compliance_case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payout_requests_compliance_status'), ['compliance_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payout_requests_referred_to_compliance'), ['referred_to_compliance'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['referred_by'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'users', ['compliance_reviewed_by'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'compliance_cases', ['compliance_case_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payout_requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_payout_requests_referred_to_compliance'))
        batch_op.drop_index(batch_op.f('ix_payout_requests_compliance_status'))
        batch_op.drop_index(batch_op.f('ix_payout_requests_compliance_case_id'))
        batch_op.drop_column('referred_by')
        batch_op.drop_column('referred_at')
        batch_op.drop_column('referred_to_compliance')
        batch_op.drop_column('compliance_reviewed_by')
        batch_op.drop_column('compliance_reviewed_at')
        batch_op.drop_column('compliance_notes')
        batch_op.drop_column('compliance_status')
        batch_op.drop_column('compliance_case_id')

    with op.batch_alter_table('organisations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_organisations_referred_to_compliance'))
        batch_op.drop_index(batch_op.f('ix_organisations_compliance_status'))
        batch_op.drop_index(batch_op.f('ix_organisations_compliance_case_id'))
        batch_op.drop_column('referred_by')
        batch_op.drop_column('referred_at')
        batch_op.drop_column('referred_to_compliance')
        batch_op.drop_column('compliance_reviewed_by')
        batch_op.drop_column('compliance_reviewed_at')
        batch_op.drop_column('compliance_notes')
        batch_op.drop_column('compliance_status')
        batch_op.drop_column('compliance_case_id')

    with op.batch_alter_table('kyc_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_kyc_records_referred_to_compliance'))
        batch_op.drop_index(batch_op.f('ix_kyc_records_compliance_status'))
        batch_op.drop_index(batch_op.f('ix_kyc_records_compliance_case_id'))
        batch_op.drop_column('referred_by')
        batch_op.drop_column('referred_at')
        batch_op.drop_column('referred_to_compliance')
        batch_op.drop_column('compliance_reviewed_by')
        batch_op.drop_column('compliance_reviewed_at')
        batch_op.drop_column('compliance_notes')
        batch_op.drop_column('compliance_status')
        batch_op.drop_column('compliance_case_id')

    with op.batch_alter_table('content_flags', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_content_flags_referred_to_compliance'))
        batch_op.drop_index(batch_op.f('ix_content_flags_compliance_case_id'))
        batch_op.drop_column('referred_by')
        batch_op.drop_column('referred_at')
        batch_op.drop_column('referred_to_compliance')
        batch_op.drop_column('compliance_case_id')

    with op.batch_alter_table('data_subject_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_subject_requests_user_id'))
        batch_op.drop_index(batch_op.f('ix_data_subject_requests_status'))
        batch_op.drop_index(batch_op.f('ix_data_subject_requests_sla_due_at'))
        batch_op.drop_index(batch_op.f('ix_data_subject_requests_request_type'))
        batch_op.drop_index(batch_op.f('ix_data_subject_requests_request_number'))
        batch_op.drop_index(batch_op.f('ix_data_subject_requests_public_id'))
        batch_op.drop_index(batch_op.f('ix_data_subject_requests_created_at'))
        batch_op.drop_index(batch_op.f('ix_data_subject_requests_assigned_to'))
        batch_op.drop_index('idx_dsr_type_status')
        batch_op.drop_index('idx_dsr_sla_due')
        batch_op.drop_index('idx_dsr_created_at')

    op.drop_table('data_subject_requests')
    with op.batch_alter_table('compliance_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_reports_status'))
        batch_op.drop_index(batch_op.f('ix_compliance_reports_report_type'))
        batch_op.drop_index(batch_op.f('ix_compliance_reports_report_number'))
        batch_op.drop_index(batch_op.f('ix_compliance_reports_public_id'))
        batch_op.drop_index(batch_op.f('ix_compliance_reports_created_at'))
        batch_op.drop_index('idx_report_type_status')
        batch_op.drop_index('idx_report_date_range')
        batch_op.drop_index('idx_report_created_at')

    op.drop_table('compliance_reports')
    with op.batch_alter_table('compliance_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_cases_user_id'))
        batch_op.drop_index(batch_op.f('ix_compliance_cases_status'))
        batch_op.drop_index(batch_op.f('ix_compliance_cases_sla_due_at'))
        batch_op.drop_index(batch_op.f('ix_compliance_cases_public_id'))
        batch_op.drop_index(batch_op.f('ix_compliance_cases_priority'))
        batch_op.drop_index(batch_op.f('ix_compliance_cases_payout_id'))
        batch_op.drop_index(batch_op.f('ix_compliance_cases_organisation_id'))
        batch_op.drop_index(batch_op.f('ix_compliance_cases_kyc_id'))
        batch_op.drop_index(batch_op.f('ix_compliance_cases_flag_id'))
        batch_op.drop_index(batch_op.f('ix_compliance_cases_created_at'))
        batch_op.drop_index(batch_op.f('ix_compliance_cases_case_type'))
        batch_op.drop_index(batch_op.f('ix_compliance_cases_case_number'))
        batch_op.drop_index(batch_op.f('ix_compliance_cases_assigned_to'))
        batch_op.drop_index('idx_case_type_status')
        batch_op.drop_index('idx_case_status_priority')
        batch_op.drop_index('idx_case_sla_due')
        batch_op.drop_index('idx_case_created_at')

    op.drop_table('compliance_cases')
    # ### end Alembic commands ###
