"""add property public_id

Revision ID: 586b35d32d53
Revises: ec4fff3b4299
Create Date: 2026-07-18 19:37:34.786073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '586b35d32d53'
down_revision = 'ec4fff3b4299'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the column as NULLABLE first so existing rows are not rejected.
    with op.batch_alter_table('accommodation_properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.String(length=64), nullable=True))

    # Backfill existing rows with UUIDs (PostgreSQL provides gen_random_uuid()).
    op.execute("UPDATE accommodation_properties SET public_id = gen_random_uuid()::text WHERE public_id IS NULL")

    # Now enforce NOT NULL and uniqueness.
    with op.batch_alter_table('accommodation_properties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accommodation_properties_public_id'), ['public_id'], unique=True)
        batch_op.alter_column('public_id', existing_type=sa.String(length=64), nullable=False)

    with op.batch_alter_table('content_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_flags_risk_score'))
        batch_op.create_index('ix_content_flags_risk_score', ['risk_score', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_flags', schema=None) as batch_op:
        batch_op.drop_index('ix_content_flags_risk_score')
        batch_op.create_index(batch_op.f('ix_content_flags_risk_score'), ['risk_score'], unique=False)

    with op.batch_alter_table('accommodation_properties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accommodation_properties_public_id'))
        batch_op.drop_column('public_id')

    # ### end Alembic commands ###
