"""add ck_inventory_block_reason_valid to accommodation_inventory_blocks

Revision ID: 5c7b672dd5e2
Revises: b8f317d76694
Create Date: 2026-08-03 10:08:55.294438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c7b672dd5e2'
down_revision = 'b8f317d76694'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accommodation_booking_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accommodation_booking_payments_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_accommodation_booking_payments_payment_reference'))
        batch_op.drop_index(batch_op.f('ix_accommodation_booking_payments_wallet_txn_id'))
        batch_op.create_unique_constraint(None, ['idempotency_key'])
        batch_op.create_unique_constraint(None, ['payment_reference'])

    with op.batch_alter_table('accommodation_bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accommodation_bookings_context_id'))
        batch_op.drop_index(batch_op.f('ix_accommodation_bookings_context_type'))
        batch_op.drop_index(batch_op.f('ix_accommodation_bookings_group_booking_id'))
        batch_op.drop_index(batch_op.f('ix_accommodation_bookings_guest_user_id'))
        batch_op.drop_index(batch_op.f('ix_accommodation_bookings_property_id'))
        batch_op.drop_index(batch_op.f('ix_accommodation_bookings_status'))

    with op.batch_alter_table('accommodation_guest_identity_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accommodation_guest_identity_profiles_user_id'))

    with op.batch_alter_table('accommodation_guest_registrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accommodation_guest_registrations_booking_id'))
        batch_op.drop_index(batch_op.f('ix_accommodation_guest_registrations_guest_user_id'))
        batch_op.drop_index(batch_op.f('ix_accommodation_guest_registrations_status'))

    with op.batch_alter_table('accommodation_inventory_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accommodation_inventory_blocks_booking_id'))
        batch_op.drop_index(batch_op.f('ix_accommodation_inventory_blocks_room_type_id'))

    with op.batch_alter_table('accommodation_properties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accommodation_properties_city'))
        batch_op.drop_index(batch_op.f('ix_accommodation_properties_is_active'))
        batch_op.drop_index(batch_op.f('ix_accommodation_properties_is_verified'))
        batch_op.drop_index(batch_op.f('ix_accommodation_properties_owner_org_id'))
        batch_op.drop_index(batch_op.f('ix_accommodation_properties_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_accommodation_properties_status'))

    with op.batch_alter_table('accommodation_property_payment_methods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accommodation_property_payment_methods_wallet_method_id'))

    with op.batch_alter_table('accommodation_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accommodation_reviews_property_id'))
        batch_op.drop_index(batch_op.f('ix_accommodation_reviews_reviewer_id'))
        batch_op.drop_index(batch_op.f('ix_accommodation_reviews_status'))

    with op.batch_alter_table('accommodation_room_holds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accommodation_room_holds_expires_at'))
        batch_op.drop_index(batch_op.f('ix_accommodation_room_holds_property_id'))
        batch_op.drop_index(batch_op.f('ix_accommodation_room_holds_room_type_id'))
        batch_op.drop_index(batch_op.f('ix_accommodation_room_holds_status'))

    with op.batch_alter_table('accommodation_room_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accommodation_room_types_is_active'))
        batch_op.drop_index(batch_op.f('ix_accommodation_room_types_property_id'))

    with op.batch_alter_table('accommodation_wishlists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accommodation_wishlists_property_id'))
        batch_op.drop_index(batch_op.f('ix_accommodation_wishlists_user_id'))

    with op.batch_alter_table('admin_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_audit_logs_action_type'))
        batch_op.drop_index(batch_op.f('ix_admin_audit_logs_admin_id'))
        batch_op.drop_index(batch_op.f('ix_admin_audit_logs_target_type'))

    with op.batch_alter_table('agent_commissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_commissions_agent_id'))

    with op.batch_alter_table('aggregators', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['api_key'])

    with op.batch_alter_table('api_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_audit_logs_service_name'))
        batch_op.drop_index(batch_op.f('ix_api_audit_logs_status'))

    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_owner_id'))
        batch_op.drop_index(batch_op.f('ix_api_keys_owner_type'))

    with op.batch_alter_table('content_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_flags_created_at'))
        batch_op.drop_index(batch_op.f('ix_content_flags_entity_id'))
        batch_op.drop_index(batch_op.f('ix_content_flags_entity_type'))
        batch_op.drop_index(batch_op.f('ix_content_flags_priority'))
        batch_op.drop_index(batch_op.f('ix_content_flags_sla_due_at'))
        batch_op.drop_index(batch_op.f('ix_content_flags_status'))

    with op.batch_alter_table('data_access_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_access_logs_accessed_by'))
        batch_op.drop_index(batch_op.f('ix_data_access_logs_subject_user_id'))

    with op.batch_alter_table('data_change_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_change_logs_changed_by'))
        batch_op.drop_index(batch_op.f('ix_data_change_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_data_change_logs_entity_type'))

    with op.batch_alter_table('emergency_access', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emergency_access_is_active'))

    with op.batch_alter_table('event_accommodation_opportunities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_accommodation_opportunities_event_id'))

    with op.batch_alter_table('event_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_assignments_community_host_id'))

    with op.batch_alter_table('event_badges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_badges_event_id'))
        batch_op.drop_index(batch_op.f('ix_event_badges_property_id'))

    with op.batch_alter_table('event_visibility', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_visibility_event_id'))
        batch_op.drop_index(batch_op.f('ix_event_visibility_property_id'))

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_current_owner_id'))
        batch_op.drop_index(batch_op.f('ix_events_is_system_event'))

    with op.batch_alter_table('financial_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_audit_logs_aml_flagged'))
        batch_op.drop_index(batch_op.f('ix_financial_audit_logs_currency'))
        batch_op.drop_index(batch_op.f('ix_financial_audit_logs_from_user_id'))
        batch_op.drop_index(batch_op.f('ix_financial_audit_logs_organisation_id'))
        batch_op.drop_index(batch_op.f('ix_financial_audit_logs_status'))

    with op.batch_alter_table('fraud_detection_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fraud_detection_config_enabled'))

    with op.batch_alter_table('fx_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fx_rates_base_currency'))
        batch_op.drop_index(batch_op.f('ix_fx_rates_quote_currency'))
        batch_op.drop_index(batch_op.f('ix_fx_rates_timestamp'))

    with op.batch_alter_table('fx_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fx_transactions_status'))
        batch_op.drop_index(batch_op.f('ix_fx_transactions_user_id'))

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_entity_id'))
        batch_op.drop_index(batch_op.f('ix_media_module'))
        batch_op.drop_index(batch_op.f('ix_media_sha256_hash'))

    with op.batch_alter_table('media_processing_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_processing_jobs_celery_task_id'))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))
        batch_op.drop_index(batch_op.f('ix_notifications_type'))
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))

    with op.batch_alter_table('org_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_org_roles_organisation_id'))

    with op.batch_alter_table('org_user_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_org_user_roles_organisation_member_id'))

    with op.batch_alter_table('organisation_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organisation_members_organisation_id'))

    with op.batch_alter_table('organisations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organisations_country'))
        batch_op.drop_index(batch_op.f('ix_organisations_is_active'))
        batch_op.drop_index(batch_op.f('ix_organisations_is_operational'))

    with op.batch_alter_table('payout_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payout_requests_agent_id'))

    with op.batch_alter_table('user_nonces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_nonces_nonce'))
        batch_op.create_index('ix_user_nonces_nonce', ['nonce'], unique=False)
        batch_op.create_unique_constraint(None, ['nonce'])

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_profiles_email'))
        batch_op.drop_index(batch_op.f('ix_user_profiles_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_user_profiles_phone_number'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_users_phone'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_profiles_phone_number'), ['phone_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_profiles_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_profiles_email'), ['email'], unique=False)

    with op.batch_alter_table('user_nonces', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index('ix_user_nonces_nonce')
        batch_op.create_index(batch_op.f('ix_user_nonces_nonce'), ['nonce'], unique=True)

    with op.batch_alter_table('payout_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payout_requests_agent_id'), ['agent_id'], unique=False)

    with op.batch_alter_table('organisations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organisations_is_operational'), ['is_operational'], unique=False)
        batch_op.create_index(batch_op.f('ix_organisations_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_organisations_country'), ['country'], unique=False)

    with op.batch_alter_table('organisation_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organisation_members_organisation_id'), ['organisation_id'], unique=False)

    with op.batch_alter_table('org_user_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_org_user_roles_organisation_member_id'), ['organisation_member_id'], unique=False)

    with op.batch_alter_table('org_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_org_roles_organisation_id'), ['organisation_id'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)

    with op.batch_alter_table('media_processing_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_processing_jobs_celery_task_id'), ['celery_task_id'], unique=False)

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_sha256_hash'), ['sha256_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_module'), ['module'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_entity_id'), ['entity_id'], unique=False)

    with op.batch_alter_table('fx_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fx_transactions_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fx_transactions_status'), ['status'], unique=False)

    with op.batch_alter_table('fx_rates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fx_rates_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_fx_rates_quote_currency'), ['quote_currency'], unique=False)
        batch_op.create_index(batch_op.f('ix_fx_rates_base_currency'), ['base_currency'], unique=False)

    with op.batch_alter_table('fraud_detection_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fraud_detection_config_enabled'), ['enabled'], unique=False)

    with op.batch_alter_table('financial_audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_audit_logs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_audit_logs_organisation_id'), ['organisation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_audit_logs_from_user_id'), ['from_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_audit_logs_currency'), ['currency'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_audit_logs_aml_flagged'), ['aml_flagged'], unique=False)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_is_system_event'), ['is_system_event'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_current_owner_id'), ['current_owner_id'], unique=False)

    with op.batch_alter_table('event_visibility', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_visibility_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_visibility_event_id'), ['event_id'], unique=False)

    with op.batch_alter_table('event_badges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_badges_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_badges_event_id'), ['event_id'], unique=False)

    with op.batch_alter_table('event_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_assignments_community_host_id'), ['community_host_id'], unique=False)

    with op.batch_alter_table('event_accommodation_opportunities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_accommodation_opportunities_event_id'), ['event_id'], unique=False)

    with op.batch_alter_table('emergency_access', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emergency_access_is_active'), ['is_active'], unique=False)

    with op.batch_alter_table('data_change_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_change_logs_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_change_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_change_logs_changed_by'), ['changed_by'], unique=False)

    with op.batch_alter_table('data_access_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_access_logs_subject_user_id'), ['subject_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_access_logs_accessed_by'), ['accessed_by'], unique=False)

    with op.batch_alter_table('content_flags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_flags_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_flags_sla_due_at'), ['sla_due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_flags_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_flags_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_flags_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_flags_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_owner_type'), ['owner_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_owner_id'), ['owner_id'], unique=False)

    with op.batch_alter_table('api_audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_audit_logs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_audit_logs_service_name'), ['service_name'], unique=False)

    with op.batch_alter_table('aggregators', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('agent_commissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_commissions_agent_id'), ['agent_id'], unique=False)

    with op.batch_alter_table('admin_audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_audit_logs_target_type'), ['target_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_audit_logs_admin_id'), ['admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_audit_logs_action_type'), ['action_type'], unique=False)

    with op.batch_alter_table('accommodation_wishlists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accommodation_wishlists_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_wishlists_property_id'), ['property_id'], unique=False)

    with op.batch_alter_table('accommodation_room_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accommodation_room_types_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_room_types_is_active'), ['is_active'], unique=False)

    with op.batch_alter_table('accommodation_room_holds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accommodation_room_holds_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_room_holds_room_type_id'), ['room_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_room_holds_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_room_holds_expires_at'), ['expires_at'], unique=False)

    with op.batch_alter_table('accommodation_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accommodation_reviews_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_reviews_reviewer_id'), ['reviewer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_reviews_property_id'), ['property_id'], unique=False)

    with op.batch_alter_table('accommodation_property_payment_methods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accommodation_property_payment_methods_wallet_method_id'), ['wallet_method_id'], unique=False)

    with op.batch_alter_table('accommodation_properties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accommodation_properties_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_properties_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_properties_owner_org_id'), ['owner_org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_properties_is_verified'), ['is_verified'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_properties_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_properties_city'), ['city'], unique=False)

    with op.batch_alter_table('accommodation_inventory_blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accommodation_inventory_blocks_room_type_id'), ['room_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_inventory_blocks_booking_id'), ['booking_id'], unique=False)

    with op.batch_alter_table('accommodation_guest_registrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accommodation_guest_registrations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_guest_registrations_guest_user_id'), ['guest_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_guest_registrations_booking_id'), ['booking_id'], unique=False)

    with op.batch_alter_table('accommodation_guest_identity_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accommodation_guest_identity_profiles_user_id'), ['user_id'], unique=True)

    with op.batch_alter_table('accommodation_bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accommodation_bookings_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_bookings_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_bookings_guest_user_id'), ['guest_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_bookings_group_booking_id'), ['group_booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_bookings_context_type'), ['context_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_bookings_context_id'), ['context_id'], unique=False)

    with op.batch_alter_table('accommodation_booking_payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('ix_accommodation_booking_payments_wallet_txn_id'), ['wallet_txn_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_booking_payments_payment_reference'), ['payment_reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_accommodation_booking_payments_idempotency_key'), ['idempotency_key'], unique=True)

    # ### end Alembic commands ###
