"""add_operational_daily_monthly_ceilings_to_wallet_system_config

Revision ID: 5cc5d7b15a1b
Revises: 1787899767
Create Date: 2026-08-29 09:08:01.742395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cc5d7b15a1b'
down_revision = '1787899767'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_system_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_daily_amount', sa.Numeric(precision=18, scale=2), nullable=True))
        batch_op.add_column(sa.Column('max_monthly_amount', sa.Numeric(precision=18, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_system_configs', schema=None) as batch_op:
        batch_op.drop_column('max_monthly_amount')
        batch_op.drop_column('max_daily_amount')

    # ### end Alembic commands ###
