"""transport reservation obligation and vehicle exclusion integrity

Revision ID: 5e80dc4ac345
Revises: a91ce8028ae4
Create Date: 2026-09-14 10:29:28.488036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e80dc4ac345'
down_revision = 'a91ce8028ae4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accommodation_guest_registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transport_booking_id', sa.BigInteger(), nullable=True))
        batch_op.create_index(batch_op.f('ix_accommodation_guest_registrations_transport_booking_id'), ['transport_booking_id'], unique=False)

    with op.batch_alter_table('transport_passengers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accommodation_booking_id', sa.BigInteger(), nullable=True))
        batch_op.create_index(batch_op.f('ix_transport_passengers_accommodation_booking_id'), ['accommodation_booking_id'], unique=False)

    with op.batch_alter_table('transport_reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_fingerprint', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('required_total_amount', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('amount_received', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transport_reservations', schema=None) as batch_op:
        batch_op.drop_column('amount_received')
        batch_op.drop_column('required_total_amount')
        batch_op.drop_column('request_fingerprint')

    with op.batch_alter_table('transport_passengers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transport_passengers_accommodation_booking_id'))
        batch_op.drop_column('accommodation_booking_id')

    with op.batch_alter_table('accommodation_guest_registrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accommodation_guest_registrations_transport_booking_id'))
        batch_op.drop_column('transport_booking_id')

    # ### end Alembic commands ###
