"""add event registration availability windows

Revision ID: 64561496dfcf
Revises: 0976b5335f95
Create Date: 2026-08-15 13:56:17.324794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64561496dfcf'
down_revision = '0976b5335f95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_opens_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('registration_closes_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('registration_closes_at')
        batch_op.drop_column('registration_opens_at')

    # ### end Alembic commands ###
