"""Add KYC verification fields to individual documents

Revision ID: 6c994e0e5f9d
Revises: b512872ef96a
Create Date: 2026-04-16 15:49:12.235934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c994e0e5f9d'
down_revision = 'b512872ef96a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
