"""add_raw_body_to_webhook_events

Revision ID: 79b4ffde1124
Revises: 120311fa7a45
Create Date: 2026-05-03 00:22:54.553341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79b4ffde1124'
down_revision = '120311fa7a45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payout_requests',
    sa.Column('request_ref', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('payment_details', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.BigInteger(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('paid_by', sa.BigInteger(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['paid_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_ref')
    )
    with op.batch_alter_table('payout_requests', schema=None) as batch_op:
        batch_op.create_index('ix_payout_requests_agent', ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payout_requests_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payout_requests_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payout_requests_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_payout_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payout_requests_updated_at'), ['updated_at'], unique=False)

    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_body', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.drop_column('raw_body')

    with op.batch_alter_table('payout_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payout_requests_updated_at'))
        batch_op.drop_index(batch_op.f('ix_payout_requests_status'))
        batch_op.drop_index(batch_op.f('ix_payout_requests_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_payout_requests_created_at'))
        batch_op.drop_index(batch_op.f('ix_payout_requests_agent_id'))
        batch_op.drop_index('ix_payout_requests_agent')

    op.drop_table('payout_requests')
    # ### end Alembic commands ###
