"""add manageable content models

Revision ID: 7a2b8c3d4e5f
Revises: 52c7be2e9c60
Create Date: 2026-04-06 07:15:26.196930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a2b8c3d4e5f'
down_revision = '52c7be2e9c60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manageable_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('editable_by_admins', sa.Boolean(), nullable=True),
    sa.Column('editable_by_org_admins', sa.Boolean(), nullable=True),
    sa.Column('editable_by_users', sa.Boolean(), nullable=True),
    sa.Column('fields_config', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('manageable_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('owned_by_org', sa.BigInteger(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['manageable_categories.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owned_by_org'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('manageable_items', schema=None) as batch_op:
        batch_op.create_index('ix_manageable_items_category_active', ['category_id', 'is_active'], unique=False)
        batch_op.create_index('ix_manageable_items_slug', ['slug'], unique=False)

    op.create_table('content_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reviewed_by', sa.BigInteger(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('submitted_by', sa.BigInteger(), nullable=False),
    sa.Column('submitted_by_org', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['manageable_categories.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['manageable_items.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_org'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_dashboard_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('layout', sa.String(length=50), nullable=True),
    sa.Column('visible_categories', sa.JSON(), nullable=True),
    sa.Column('featured_items', sa.JSON(), nullable=True),
    sa.Column('notify_new_content', sa.Boolean(), nullable=True),
    sa.Column('notify_approvals', sa.Boolean(), nullable=True),
    sa.Column('notify_rejections', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_dashboard_configs')
    op.drop_table('content_submissions')
    with op.batch_alter_table('manageable_items', schema=None) as batch_op:
        batch_op.drop_index('ix_manageable_items_slug')
        batch_op.drop_index('ix_manageable_items_category_active')

    op.drop_table('manageable_items')
    op.drop_table('manageable_categories')
    # ### end Alembic commands ###
