"""Add trust-based security settings to EventSettings

Revision ID: 7d2872a2c358
Revises: ceadd442d369
Create Date: 2026-05-09 00:11:25.559356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d2872a2c358'
down_revision = 'ceadd442d369'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_flags_risk_score'))
        batch_op.create_index('ix_content_flags_risk_score', ['risk_score', 'status'], unique=False)

    # First, add columns as nullable with server defaults
    with op.batch_alter_table('event_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enable_trust_based_publishing', sa.Boolean(), server_default=sa.text('true'), nullable=False))
        batch_op.add_column(sa.Column('high_trust_threshold', sa.Integer(), server_default=sa.text('70'), nullable=False))
        batch_op.add_column(sa.Column('medium_trust_threshold', sa.Integer(), server_default=sa.text('40'), nullable=False))
        batch_op.add_column(sa.Column('enable_role_bypass', sa.Boolean(), server_default=sa.text('true'), nullable=False))
        batch_op.add_column(sa.Column('enable_kyc_boost', sa.Boolean(), server_default=sa.text('true'), nullable=False))
        batch_op.add_column(sa.Column('enable_account_age_boost', sa.Boolean(), server_default=sa.text('true'), nullable=False))
        batch_op.add_column(sa.Column('enable_event_history_boost', sa.Boolean(), server_default=sa.text('true'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_settings', schema=None) as batch_op:
        batch_op.drop_column('enable_event_history_boost')
        batch_op.drop_column('enable_account_age_boost')
        batch_op.drop_column('enable_kyc_boost')
        batch_op.drop_column('enable_role_bypass')
        batch_op.drop_column('medium_trust_threshold')
        batch_op.drop_column('high_trust_threshold')
        batch_op.drop_column('enable_trust_based_publishing')

    with op.batch_alter_table('content_flags', schema=None) as batch_op:
        batch_op.drop_index('ix_content_flags_risk_score')
        batch_op.create_index(batch_op.f('ix_content_flags_risk_score'), ['risk_score'], unique=False)

    # ### end Alembic commands ###
