"""add accommodation room holds_version_2

Revision ID: 8045e2548d4b
Revises: acf73a88632f
Create Date: 2026-07-31 18:33:25.850612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8045e2548d4b'
down_revision = 'acf73a88632f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accommodation_room_holds',
    sa.Column('property_id', sa.BigInteger(), nullable=False),
    sa.Column('room_type_id', sa.BigInteger(), nullable=True),
    sa.Column('booking_id', sa.BigInteger(), nullable=True),
    sa.Column('guest_user_id', sa.BigInteger(), nullable=True),
    sa.Column('check_in', sa.Date(), nullable=False),
    sa.Column('check_out', sa.Date(), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('hold_minutes', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('release_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'released', 'expired', 'converted')", name='ck_room_hold_status_valid'),
    sa.CheckConstraint('check_out > check_in', name='ck_room_hold_dates_valid'),
    sa.CheckConstraint('hold_minutes > 0', name='ck_room_hold_minutes_positive'),
    sa.ForeignKeyConstraint(['booking_id'], ['accommodation_bookings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['guest_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['accommodation_properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_type_id'], ['accommodation_room_types.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accommodation_room_holds', schema=None) as batch_op:
        batch_op.create_index('idx_room_hold_expires', ['status', 'expires_at'], unique=False)
        batch_op.create_index('idx_room_hold_property_dates', ['property_id', 'check_in', 'check_out'], unique=False)
        batch_op.create_index('idx_room_hold_room_type_dates', ['room_type_id', 'check_in', 'check_out'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_room_holds_booking_id'), ['booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_room_holds_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_room_holds_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_room_holds_guest_user_id'), ['guest_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_room_holds_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_room_holds_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_room_holds_room_type_id'), ['room_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_room_holds_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_room_holds_updated_at'), ['updated_at'], unique=False)

    with op.batch_alter_table('aggregators', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aggregators_api_key'))
        batch_op.create_index(batch_op.f('ix_aggregators_api_key'), ['api_key'], unique=True)

    with op.batch_alter_table('user_nonces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_nonces_nonce'))
        batch_op.create_index('ix_user_nonces_nonce', ['nonce'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_nonces', schema=None) as batch_op:
        batch_op.drop_index('ix_user_nonces_nonce')
        batch_op.create_index(batch_op.f('ix_user_nonces_nonce'), ['nonce'], unique=True)

    with op.batch_alter_table('aggregators', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aggregators_api_key'))
        batch_op.create_index(batch_op.f('ix_aggregators_api_key'), ['api_key'], unique=False)

    with op.batch_alter_table('accommodation_room_holds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accommodation_room_holds_updated_at'))
        batch_op.drop_index(batch_op.f('ix_accommodation_room_holds_status'))
        batch_op.drop_index(batch_op.f('ix_accommodation_room_holds_room_type_id'))
        batch_op.drop_index(batch_op.f('ix_accommodation_room_holds_property_id'))
        batch_op.drop_index(batch_op.f('ix_accommodation_room_holds_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_accommodation_room_holds_guest_user_id'))
        batch_op.drop_index(batch_op.f('ix_accommodation_room_holds_expires_at'))
        batch_op.drop_index(batch_op.f('ix_accommodation_room_holds_created_at'))
        batch_op.drop_index(batch_op.f('ix_accommodation_room_holds_booking_id'))
        batch_op.drop_index('idx_room_hold_room_type_dates')
        batch_op.drop_index('idx_room_hold_property_dates')
        batch_op.drop_index('idx_room_hold_expires')

    op.drop_table('accommodation_room_holds')
    # ### end Alembic commands ###
