"""add booking approval and property policy tracking fields

Revision ID: 8120b21c333e
Revises: 273c374bade0
Create Date: 2026-07-23 17:56:36.956525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8120b21c333e'
down_revision = '273c374bade0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accommodation_bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approval_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('approved_by_user_id', sa.BigInteger(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['approved_by_user_id'], ['id'])

    with op.batch_alter_table('accommodation_properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('require_host_approval', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('policy_violations', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('auto_suspend_threshold', sa.Integer(), nullable=False, server_default='5'))
        batch_op.add_column(sa.Column('is_suspended', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('suspension_reason', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_accommodation_properties_is_suspended'), ['is_suspended'], unique=False)

    with op.batch_alter_table('content_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_flags_risk_score'))
        batch_op.create_index(batch_op.f('ix_content_flags_risk_score'), ['risk_score'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_flags_risk_score'))
        batch_op.create_index(batch_op.f('ix_content_flags_risk_score'), ['risk_score', 'status'], unique=False)

    with op.batch_alter_table('accommodation_properties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accommodation_properties_is_suspended'))
        batch_op.drop_column('suspension_reason')
        batch_op.drop_column('is_suspended')
        batch_op.drop_column('auto_suspend_threshold')
        batch_op.drop_column('policy_violations')
        batch_op.drop_column('require_host_approval')

    with op.batch_alter_table('accommodation_bookings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('approved_by_user_id')
        batch_op.drop_column('approval_reason')

    # ### end Alembic commands ###
