"""add_seamless_booking_registration_and_request_features

Revision ID: 880265998f89
Revises: fc0f4f135025
Create Date: 2026-08-12 11:46:19.081670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '880265998f89'
down_revision = 'fc0f4f135025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accommodation_booking_registration_links',
    sa.Column('booking_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('max_registrants', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['accommodation_bookings.id'], name='fk_registration_link_booking', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id', name='uq_registration_link_booking')
    )
    with op.batch_alter_table('accommodation_booking_registration_links', schema=None) as batch_op:
        batch_op.create_index('idx_registration_link_token', ['token_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_booking_registration_links_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_booking_registration_links_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_accommodation_booking_registration_links_updated_at'), ['updated_at'], unique=False)

    op.create_table('accommodation_booking_special_requests',
    sa.Column('booking_id', sa.BigInteger(), nullable=False),
    sa.Column('guest_registration_id', sa.BigInteger(), nullable=True),
    sa.Column('requested_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('request_type', sa.String(length=50), nullable=True),
    sa.Column('request_text', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('host_response_note', sa.Text(), nullable=True),
    sa.Column('responded_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['accommodation_bookings.id'], name='fk_special_request_booking', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guest_registration_id'], ['accommodation_guest_registrations.id'], name='fk_special_request_guest_registration', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], name='fk_special_request_requested_by_user'),
    sa.ForeignKeyConstraint(['responded_by_user_id'], ['users.id'], name='fk_special_request_responded_by_user'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accommodation_booking_special_requests', schema=None) as batch_op:
        batch_op.create_index('idx_special_request_booking', ['booking_id'], unique=False)
        batch_op.create_index('idx_special_request_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_booking_special_requests_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_booking_special_requests_updated_at'), ['updated_at'], unique=False)

    with op.batch_alter_table('accommodation_bookings', schema=None) as batch_op:
        batch_op.alter_column('guest_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('guest_email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('accommodation_guest_registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
        batch_op.add_column(sa.Column('is_placeholder', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('replaces_registration_id', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('removed_by_user_id', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('removed_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('import_batch_id', sa.String(length=64), nullable=True))
        batch_op.create_index('idx_guest_reg_active', ['booking_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_guest_registrations_import_batch_id'), ['import_batch_id'], unique=False)
        batch_op.create_foreign_key('fk_guest_reg_replaces_registration', 'accommodation_guest_registrations', ['replaces_registration_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_guest_reg_removed_by_user', 'users', ['removed_by_user_id'], ['id'])

    with op.batch_alter_table('accommodation_property_booking_policies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available_request_options', sa.JSON(), server_default='[]', nullable=False))

    with op.batch_alter_table('accommodation_property_payment_methods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_currency', sa.String(length=3), nullable=True))

    with op.batch_alter_table('payment_method_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allowed_timings', sa.JSON(), server_default='[]', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_method_configs', schema=None) as batch_op:
        batch_op.drop_column('allowed_timings')

    with op.batch_alter_table('accommodation_property_payment_methods', schema=None) as batch_op:
        batch_op.drop_column('preferred_currency')

    with op.batch_alter_table('accommodation_property_booking_policies', schema=None) as batch_op:
        batch_op.drop_column('available_request_options')

    with op.batch_alter_table('accommodation_guest_registrations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_guest_reg_removed_by_user', type_='foreignkey')
        batch_op.drop_constraint('fk_guest_reg_replaces_registration', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_accommodation_guest_registrations_import_batch_id'))
        batch_op.drop_index('idx_guest_reg_active')
        batch_op.drop_column('import_batch_id')
        batch_op.drop_column('removed_reason')
        batch_op.drop_column('removed_by_user_id')
        batch_op.drop_column('removed_at')
        batch_op.drop_column('replaces_registration_id')
        batch_op.drop_column('is_placeholder')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('accommodation_bookings', schema=None) as batch_op:
        batch_op.alter_column('guest_email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('guest_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('accommodation_booking_special_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accommodation_booking_special_requests_updated_at'))
        batch_op.drop_index(batch_op.f('ix_accommodation_booking_special_requests_is_deleted'))
        batch_op.drop_index('idx_special_request_status')
        batch_op.drop_index('idx_special_request_booking')

    op.drop_table('accommodation_booking_special_requests')
    with op.batch_alter_table('accommodation_booking_registration_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accommodation_booking_registration_links_updated_at'))
        batch_op.drop_index(batch_op.f('ix_accommodation_booking_registration_links_token_hash'))
        batch_op.drop_index(batch_op.f('ix_accommodation_booking_registration_links_is_deleted'))
        batch_op.drop_index('idx_registration_link_token')

    op.drop_table('accommodation_booking_registration_links')
    # ### end Alembic commands ###
