"""aggregators_integration

Revision ID: 8eddbe3d8a03
Revises: 559ed1dc362b
Create Date: 2026-05-07 19:36:16.390345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eddbe3d8a03'
down_revision = '559ed1dc362b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create wallet_transactions table for comprehensive payment tracking
    op.create_table('wallet_transactions',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('transaction_id', sa.String(length=100), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column('currency', sa.String(length=3), nullable=False),
        sa.Column('status', sa.Enum('pending', 'completed', 'failed', 'cancelled', name='transaction_status'), nullable=False),
        sa.Column('gateway_type', sa.String(length=50), nullable=True),
        sa.Column('payment_method', sa.String(length=100), nullable=True),
        sa.Column('payment_provider', sa.String(length=100), nullable=True),
        sa.Column('provider_reference', sa.String(length=200), nullable=True),
        sa.Column('provider_request_id', sa.String(length=200), nullable=True),
        sa.Column('to_user_id', sa.BigInteger(), nullable=True),
        sa.Column('to_balance_before', sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column('from_user_id', sa.BigInteger(), nullable=True),
        sa.Column('from_balance_before', sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column('ip_address', sa.String(length=45), nullable=True),
        sa.Column('user_agent', sa.Text(), nullable=True),
        sa.Column('api_call_status', sa.Enum('SUCCESS', 'FAILED', 'TIMEOUT', name='api_call_status'), nullable=True),
        sa.Column('response_time_ms', sa.Integer(), nullable=True),
        sa.Column('metadata', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('transaction_id'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], )
    )
    op.create_index('ix_wallet_transactions_user_id', 'wallet_transactions', ['user_id'], unique=False)
    op.create_index('ix_wallet_transactions_status', 'wallet_transactions', ['status'], unique=False)
    op.create_index('ix_wallet_transactions_created_at', 'wallet_transactions', ['created_at'], unique=False)
    op.create_index('ix_wallet_transactions_gateway_type', 'wallet_transactions', ['gateway_type'], unique=False)
    
    # Create wallet_balances table
    op.create_table('wallet_balances',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('balance', sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column('currency', sa.String(length=3), nullable=False),
        sa.Column('available_balance', sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column('frozen_balance', sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_index('ix_wallet_balances_user_id', 'wallet_balances', ['user_id'], unique=True)
    
    # Create payment_gateway_configs table
    op.create_table('payment_gateway_configs',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('gateway_name', sa.String(length=50), nullable=False),
        sa.Column('is_enabled', sa.Boolean(), nullable=False),
        sa.Column('environment', sa.String(length=20), nullable=False),
        sa.Column('config_data', sa.JSON(), nullable=True),
        sa.Column('fee_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column('fixed_fee', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('min_amount', sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column('max_amount', sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('gateway_name')
    )
    
    # Create regulator_access_codes table
    op.create_table('regulator_access_codes',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('access_code', sa.String(length=50), nullable=False),
        sa.Column('regulator_id', sa.String(length=100), nullable=False),
        sa.Column('permissions', sa.JSON(), nullable=False),
        sa.Column('created_by', sa.BigInteger(), nullable=False),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.Column('access_count', sa.Integer(), nullable=False),
        sa.Column('max_accesses', sa.Integer(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('revoked_at', sa.DateTime(), nullable=True),
        sa.Column('revoked_by', sa.BigInteger(), nullable=True),
        sa.Column('revocation_reason', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('access_code'),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['revoked_by'], ['users.id'], )
    )
    op.create_index('ix_regulator_access_codes_regulator_id', 'regulator_access_codes', ['regulator_id'], unique=False)
    op.create_index('ix_regulator_access_codes_expires_at', 'regulator_access_codes', ['expires_at'], unique=False)
    
    # Create aggregator_webhook_configs table
    op.create_table('aggregator_webhook_configs',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('aggregator_id', sa.String(length=100), nullable=False),
        sa.Column('webhook_url', sa.String(length=500), nullable=False),
        sa.Column('secret_key', sa.String(length=200), nullable=False),
        sa.Column('events', sa.JSON(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('aggregator_id')
    )
    
    # Create delegation_records table
    op.create_table('delegation_records',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('delegation_id', sa.String(length=50), nullable=False),
        sa.Column('delegator_id', sa.BigInteger(), nullable=False),
        sa.Column('delegatee_id', sa.BigInteger(), nullable=False),
        sa.Column('delegator_role', sa.String(length=50), nullable=False),
        sa.Column('delegatee_role', sa.String(length=50), nullable=False),
        sa.Column('scopes', sa.JSON(), nullable=False),
        sa.Column('duration_hours', sa.Integer(), nullable=False),
        sa.Column('reason', sa.Text(), nullable=False),
        sa.Column('approved_by', sa.BigInteger(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('revoked_at', sa.DateTime(), nullable=True),
        sa.Column('revoked_by', sa.BigInteger(), nullable=True),
        sa.Column('revocation_reason', sa.Text(), nullable=True),
        sa.Column('expired_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('delegation_id'),
        sa.ForeignKeyConstraint(['delegator_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['delegatee_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['revoked_by'], ['users.id'], )
    )
    op.create_index('ix_delegation_records_delegator_id', 'delegation_records', ['delegator_id'], unique=False)
    op.create_index('ix_delegation_records_delegatee_id', 'delegation_records', ['delegatee_id'], unique=False)
    op.create_index('ix_delegation_records_expires_at', 'delegation_records', ['expires_at'], unique=False)
    
    # Add payment gateway settings to existing system_settings table
    op.add_column('system_settings', sa.Column('paypal_enabled', sa.Boolean(), nullable=True))
    op.add_column('system_settings', sa.Column('paypal_client_id', sa.String(length=200), nullable=True))
    op.add_column('system_settings', sa.Column('paypal_environment', sa.String(length=20), nullable=True))
    op.add_column('system_settings', sa.Column('alipay_enabled', sa.Boolean(), nullable=True))
    op.add_column('system_settings', sa.Column('alipay_app_id', sa.String(length=200), nullable=True))
    op.add_column('system_settings', sa.Column('alipay_environment', sa.String(length=20), nullable=True))
    op.add_column('system_settings', sa.Column('flutterwave_enabled', sa.Boolean(), nullable=True))
    op.add_column('system_settings', sa.Column('flutterwave_public_key', sa.String(length=200), nullable=True))
    op.add_column('system_settings', sa.Column('flutterwave_environment', sa.String(length=20), nullable=True))
    op.add_column('system_settings', sa.Column('paystack_enabled', sa.Boolean(), nullable=True))
    op.add_column('system_settings', sa.Column('paystack_public_key', sa.String(length=200), nullable=True))
    op.add_column('system_settings', sa.Column('paystack_environment', sa.String(length=20), nullable=True))
    op.add_column('system_settings', sa.Column('mobile_money_enabled', sa.Boolean(), nullable=True))
    op.add_column('system_settings', sa.Column('mtn_ug_api_key', sa.String(length=200), nullable=True))
    op.add_column('system_settings', sa.Column('airtel_ug_api_key', sa.String(length=200), nullable=True))
    op.add_column('system_settings', sa.Column('mpesa_api_key', sa.String(length=200), nullable=True))
    op.add_column('system_settings', sa.Column('visa_enabled', sa.Boolean(), nullable=True))
    op.add_column('system_settings', sa.Column('visa_merchant_id', sa.String(length=200), nullable=True))
    op.add_column('system_settings', sa.Column('visa_environment', sa.String(length=20), nullable=True))
    op.add_column('system_settings', sa.Column('wechat_enabled', sa.Boolean(), nullable=True))
    op.add_column('system_settings', sa.Column('wechat_app_id', sa.String(length=200), nullable=True))
    op.add_column('system_settings', sa.Column('wechat_environment', sa.String(length=20), nullable=True))
    
    # Add wallet configuration settings
    op.add_column('system_settings', sa.Column('wallet_min_transaction', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('system_settings', sa.Column('wallet_max_transaction', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('system_settings', sa.Column('wallet_daily_limit', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('system_settings', sa.Column('wallet_monthly_limit', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('system_settings', sa.Column('wallet_max_balance', sa.Numeric(precision=15, scale=2), nullable=True))
    
    # Add fee configuration settings
    op.add_column('system_settings', sa.Column('paypal_fee', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('system_settings', sa.Column('paypal_fixed_fee', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('system_settings', sa.Column('alipay_fee', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('system_settings', sa.Column('flutterwave_fee', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('system_settings', sa.Column('paystack_fee', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('system_settings', sa.Column('mobile_money_fee', sa.Numeric(precision=5, scale=2), nullable=True))
    
    # Add security configuration settings
    op.add_column('system_settings', sa.Column('wallet_2fa_enabled', sa.Boolean(), nullable=True))
    op.add_column('system_settings', sa.Column('wallet_pin_threshold', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('system_settings', sa.Column('wallet_max_failed_attempts', sa.Integer(), nullable=True))
    op.add_column('system_settings', sa.Column('wallet_lockout_duration', sa.Integer(), nullable=True))
    
    # Add delegation configuration settings
    op.add_column('system_settings', sa.Column('delegation_enabled', sa.Boolean(), nullable=True))
    op.add_column('system_settings', sa.Column('admin_delegation_approval', sa.Boolean(), nullable=True))
    op.add_column('system_settings', sa.Column('max_delegation_duration', sa.Integer(), nullable=True))
    op.add_column('system_settings', sa.Column('auto_expire_delegations', sa.Boolean(), nullable=True))
    
    # Add compliance configuration settings
    op.add_column('system_settings', sa.Column('aml_enabled', sa.Boolean(), nullable=True))
    op.add_column('system_settings', sa.Column('aml_threshold', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('system_settings', sa.Column('kyc_enabled', sa.Boolean(), nullable=True))
    op.add_column('system_settings', sa.Column('kyc_required_level', sa.Integer(), nullable=True))
    op.add_column('system_settings', sa.Column('regulator_access_enabled', sa.Boolean(), nullable=True))
    op.add_column('system_settings', sa.Column('audit_retention_days', sa.Integer(), nullable=True))
    
    # Note: Old indexes from kyc_records and mfa_secrets have been removed in previous migrations
    # Skipping index dropping to avoid conflicts

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop new tables
    op.drop_table('delegation_records')
    op.drop_table('aggregator_webhook_configs')
    op.drop_table('regulator_access_codes')
    op.drop_table('payment_gateway_configs')
    op.drop_table('wallet_balances')
    op.drop_table('wallet_transactions')
    
    # Drop new columns from system_settings table
    op.drop_column('system_settings', 'audit_retention_days')
    op.drop_column('system_settings', 'regulator_access_enabled')
    op.drop_column('system_settings', 'kyc_required_level')
    op.drop_column('system_settings', 'kyc_enabled')
    op.drop_column('system_settings', 'aml_threshold')
    op.drop_column('system_settings', 'aml_enabled')
    op.drop_column('system_settings', 'auto_expire_delegations')
    op.drop_column('system_settings', 'max_delegation_duration')
    op.drop_column('system_settings', 'admin_delegation_approval')
    op.drop_column('system_settings', 'delegation_enabled')
    op.drop_column('system_settings', 'wallet_lockout_duration')
    op.drop_column('system_settings', 'wallet_max_failed_attempts')
    op.drop_column('system_settings', 'wallet_pin_threshold')
    op.drop_column('system_settings', 'wallet_2fa_enabled')
    op.drop_column('system_settings', 'mobile_money_fee')
    op.drop_column('system_settings', 'paystack_fee')
    op.drop_column('system_settings', 'flutterwave_fee')
    op.drop_column('system_settings', 'alipay_fee')
    op.drop_column('system_settings', 'paypal_fixed_fee')
    op.drop_column('system_settings', 'paypal_fee')
    op.drop_column('system_settings', 'wechat_environment')
    op.drop_column('system_settings', 'wechat_app_id')
    op.drop_column('system_settings', 'wechat_enabled')
    op.drop_column('system_settings', 'visa_environment')
    op.drop_column('system_settings', 'visa_merchant_id')
    op.drop_column('system_settings', 'visa_enabled')
    op.drop_column('system_settings', 'mpesa_api_key')
    op.drop_column('system_settings', 'airtel_ug_api_key')
    op.drop_column('system_settings', 'mtn_ug_api_key')
    op.drop_column('system_settings', 'mobile_money_enabled')
    op.drop_column('system_settings', 'paystack_environment')
    op.drop_column('system_settings', 'paystack_public_key')
    op.drop_column('system_settings', 'paystack_enabled')
    op.drop_column('system_settings', 'flutterwave_environment')
    op.drop_column('system_settings', 'flutterwave_public_key')
    op.drop_column('system_settings', 'flutterwave_enabled')
    op.drop_column('system_settings', 'alipay_environment')
    op.drop_column('system_settings', 'alipay_app_id')
    op.drop_column('system_settings', 'alipay_enabled')
    op.drop_column('system_settings', 'paypal_environment')
    op.drop_column('system_settings', 'paypal_client_id')
    op.drop_column('system_settings', 'paypal_enabled')
    
    # Recreate old indexes
    with op.batch_alter_table('mfa_secrets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mfa_secrets_user_active'), ['user_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_mfa_secrets_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('kyc_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kyc_records_risk'), ['enhanced_risk_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_kyc_records_expiry'), ['expiry_date'], unique=False)

    # ### end Alembic commands ###
