"""aml_regulatory_and_biginteger_pk

Revision ID: 961bd8f150b3
Revises: 366d06e59f9c
Create Date: 2026-08-11 10:17:10.179828

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '961bd8f150b3'
down_revision = '366d06e59f9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aml_jurisdiction_profiles',
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('country_name', sa.String(length=120), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('cash_threshold_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency_point_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cash_threshold_points', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('str_sla_working_days', sa.Integer(), nullable=False),
    sa.Column('structuring_band_percent', sa.Integer(), nullable=False),
    sa.Column('supported_report_types', sa.JSON(), nullable=False),
    sa.Column('identifier_types', sa.JSON(), nullable=False),
    sa.Column('retention_years', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('retention_years >= 0 AND retention_years <= 50', name='ck_jurisdiction_retention_range'),
    sa.CheckConstraint('str_sla_working_days >= 0 AND str_sla_working_days <= 30', name='ck_jurisdiction_sla_range'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aml_jurisdiction_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aml_jurisdiction_profiles_country_code'), ['country_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_aml_jurisdiction_profiles_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_aml_jurisdiction_profiles_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_aml_jurisdiction_profiles_updated_at'), ['updated_at'], unique=False)

    op.create_table('aml_attestations',
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('attestation_type', sa.String(length=40), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=True),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.Column('attested_by', sa.BigInteger(), nullable=False),
    sa.Column('attested_at', sa.DateTime(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('document_ref', sa.String(length=120), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("attestation_type IN ('mlro_quarterly','program_effectiveness','tms_review')", name='ck_aml_attestation_type'),
    sa.CheckConstraint("status IN ('draft','submitted','archived')", name='ck_aml_attestation_status'),
    sa.ForeignKeyConstraint(['attested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aml_attestations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aml_attestations_attested_by'), ['attested_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_aml_attestations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_aml_attestations_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_aml_attestations_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_aml_attestations_updated_at'), ['updated_at'], unique=False)

    op.create_table('aml_monitoring_scenarios',
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('risk_weight', sa.Integer(), nullable=False),
    sa.Column('threshold_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('last_calibrated_at', sa.DateTime(), nullable=True),
    sa.Column('last_calibrated_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('amount','velocity','pattern','geography','sanctions','pep')", name='ck_monitoring_scenario_category'),
    sa.ForeignKeyConstraint(['last_calibrated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('aml_monitoring_scenarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aml_monitoring_scenarios_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_aml_monitoring_scenarios_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_aml_monitoring_scenarios_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_aml_monitoring_scenarios_updated_at'), ['updated_at'], unique=False)

    op.create_table('aml_regulatory_reports',
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('report_number', sa.String(length=50), nullable=False),
    sa.Column('jurisdiction_id', sa.BigInteger(), nullable=True),
    sa.Column('report_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('subject_type', sa.String(length=20), nullable=False),
    sa.Column('subject_user_id', sa.BigInteger(), nullable=True),
    sa.Column('subject_org_id', sa.BigInteger(), nullable=True),
    sa.Column('subject_identifier', sa.String(length=120), nullable=True),
    sa.Column('subject_name', sa.String(length=255), nullable=True),
    sa.Column('related_transaction_id', sa.String(length=64), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('suspicion_formed_at', sa.DateTime(), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('filed_at', sa.DateTime(), nullable=True),
    sa.Column('filed_by', sa.BigInteger(), nullable=True),
    sa.Column('external_reference', sa.String(length=120), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('xml_content', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("report_type IN ('str','sar','ctr','lctr','iwtr','tfr','alctr')", name='ck_regulatory_report_type'),
    sa.CheckConstraint("status IN ('draft','submitted','accepted','rejected','filed')", name='ck_regulatory_report_status'),
    sa.CheckConstraint("subject_type IN ('individual','organisation','transaction')", name='ck_regulatory_report_subject_type'),
    sa.ForeignKeyConstraint(['filed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['jurisdiction_id'], ['aml_jurisdiction_profiles.id'], ),
    sa.ForeignKeyConstraint(['subject_org_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['subject_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aml_regulatory_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aml_regulatory_reports_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_aml_regulatory_reports_due_at'), ['due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_aml_regulatory_reports_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_aml_regulatory_reports_jurisdiction_id'), ['jurisdiction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_aml_regulatory_reports_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_aml_regulatory_reports_related_transaction_id'), ['related_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_aml_regulatory_reports_report_number'), ['report_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_aml_regulatory_reports_report_type'), ['report_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_aml_regulatory_reports_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_aml_regulatory_reports_subject_org_id'), ['subject_org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_aml_regulatory_reports_subject_user_id'), ['subject_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_aml_regulatory_reports_updated_at'), ['updated_at'], unique=False)

    op.create_table('aml_retention_policies',
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('resource_type', sa.String(length=60), nullable=False),
    sa.Column('retention_years', sa.Integer(), nullable=False),
    sa.Column('auto_purge', sa.Boolean(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.BigInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("resource_type IN ('kyc','transaction','regulatory_report','aml_screening','audit_log')", name='ck_retention_resource_type'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_type')
    )
    with op.batch_alter_table('aml_retention_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aml_retention_policies_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_aml_retention_policies_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_aml_retention_policies_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_aml_retention_policies_updated_at'), ['updated_at'], unique=False)

    op.create_table('aml_screening_results',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.Column('screening_type', sa.String(length=50), nullable=False),
    sa.Column('screening_date', sa.DateTime(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('sanctions_checked', sa.Boolean(), nullable=False),
    sa.Column('sanctions_matches', sa.JSON(), nullable=True),
    sa.Column('pep_checked', sa.Boolean(), nullable=False),
    sa.Column('pep_matches', sa.JSON(), nullable=True),
    sa.Column('risk_factors', sa.JSON(), nullable=True),
    sa.Column('alerts_triggered', sa.JSON(), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.Column('reviewed_by', sa.BigInteger(), nullable=True),
    sa.Column('reviewed_date', sa.DateTime(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aml_screening_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aml_screening_results_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_aml_screening_results_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_aml_screening_results_risk_level'), ['risk_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_aml_screening_results_transaction_id'), ['transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_aml_screening_results_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_aml_screening_results_user_id'), ['user_id'], unique=False)

    op.create_table('aml_terminated_entities',
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('registration_number', sa.String(length=120), nullable=True),
    sa.Column('national_id', sa.String(length=120), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('reason_code', sa.String(length=40), nullable=True),
    sa.Column('reason_text', sa.Text(), nullable=True),
    sa.Column('terminated_at', sa.DateTime(), nullable=True),
    sa.Column('added_by', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("entity_type IN ('organisation','individual')", name='ck_terminated_entity_type'),
    sa.CheckConstraint("source IN ('match','vmss','internal','manual','regulator')", name='ck_terminated_entity_source'),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aml_terminated_entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aml_terminated_entities_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_aml_terminated_entities_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_aml_terminated_entities_national_id'), ['national_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_aml_terminated_entities_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_aml_terminated_entities_registration_number'), ['registration_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_aml_terminated_entities_updated_at'), ['updated_at'], unique=False)

    op.create_table('aml_training_records',
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('training_module', sa.String(length=120), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('certificate_ref', sa.String(length=120), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_by', sa.String(length=120), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aml_training_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aml_training_records_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_aml_training_records_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_aml_training_records_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_aml_training_records_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_aml_training_records_user_id'), ['user_id'], unique=False)

    op.create_table('aml_transaction_monitor',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('monitoring_date', sa.DateTime(), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('total_transactions', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('average_amount', sa.Float(), nullable=False),
    sa.Column('max_amount', sa.Float(), nullable=False),
    sa.Column('large_transactions_count', sa.Integer(), nullable=False),
    sa.Column('high_frequency_flag', sa.Boolean(), nullable=False),
    sa.Column('unusual_pattern_flag', sa.Boolean(), nullable=False),
    sa.Column('rounding_flag', sa.Boolean(), nullable=False),
    sa.Column('structuring_flag', sa.Boolean(), nullable=False),
    sa.Column('countries_involved', sa.JSON(), nullable=True),
    sa.Column('high_risk_countries', sa.JSON(), nullable=True),
    sa.Column('alert_level', sa.String(length=20), nullable=False),
    sa.Column('alerts_generated', sa.JSON(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aml_transaction_monitor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aml_transaction_monitor_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_aml_transaction_monitor_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_aml_transaction_monitor_monitoring_date'), ['monitoring_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_aml_transaction_monitor_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_aml_transaction_monitor_user_id'), ['user_id'], unique=False)

    op.create_table('fraud_alerts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('transaction_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('patterns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.BigInteger(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("action IN ('send_funds', 'withdraw_funds', 'deposit', 'transfer', 'change_email', 'change_phone', 'change_password', 'wallet_activation')", name='ck_fraud_alert_action_valid'),
    sa.CheckConstraint("status IN ('open', 'reviewing', 'resolved', 'dismissed', 'escalated')", name='ck_fraud_alert_status_valid'),
    sa.CheckConstraint('risk_score >= 0 AND risk_score <= 100', name='ck_fraud_alert_risk_score_range'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fraud_alerts', schema=None) as batch_op:
        batch_op.create_index('ix_fraud_alert_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_fraud_alert_risk_score', ['risk_score'], unique=False)
        batch_op.create_index('ix_fraud_alert_status', ['status'], unique=False)
        batch_op.create_index('ix_fraud_alert_transaction_id', ['transaction_id'], unique=False)
        batch_op.create_index('ix_fraud_alert_user_id', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fraud_alerts_transaction_id'), ['transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fraud_alerts_user_id'), ['user_id'], unique=False)

    op.create_table('aml_backtest_runs',
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('scenario_id', sa.BigInteger(), nullable=True),
    sa.Column('run_at', sa.DateTime(), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=True),
    sa.Column('window_end', sa.DateTime(), nullable=True),
    sa.Column('transactions_scored', sa.Integer(), nullable=False),
    sa.Column('alerts_generated', sa.Integer(), nullable=False),
    sa.Column('true_positives', sa.Integer(), nullable=True),
    sa.Column('false_positives', sa.Integer(), nullable=True),
    sa.Column('precision_score', sa.Float(), nullable=True),
    sa.Column('recall_score', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['aml_monitoring_scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aml_backtest_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aml_backtest_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_aml_backtest_runs_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_aml_backtest_runs_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_aml_backtest_runs_scenario_id'), ['scenario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_aml_backtest_runs_updated_at'), ['updated_at'], unique=False)

    op.create_table('aml_ctr_alerts',
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('jurisdiction_id', sa.BigInteger(), nullable=True),
    sa.Column('alert_type', sa.String(length=20), nullable=False),
    sa.Column('period_date', sa.Date(), nullable=False),
    sa.Column('aggregated_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('transaction_count', sa.Integer(), nullable=False),
    sa.Column('threshold_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reported_report_id', sa.BigInteger(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("alert_type IN ('ctr','structuring')", name='ck_ctr_alert_type'),
    sa.CheckConstraint("status IN ('open','reported','dismissed')", name='ck_ctr_alert_status'),
    sa.ForeignKeyConstraint(['jurisdiction_id'], ['aml_jurisdiction_profiles.id'], ),
    sa.ForeignKeyConstraint(['reported_report_id'], ['aml_regulatory_reports.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aml_ctr_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aml_ctr_alerts_alert_type'), ['alert_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_aml_ctr_alerts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_aml_ctr_alerts_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_aml_ctr_alerts_jurisdiction_id'), ['jurisdiction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_aml_ctr_alerts_period_date'), ['period_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_aml_ctr_alerts_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_aml_ctr_alerts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_aml_ctr_alerts_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_aml_ctr_alerts_user_id'), ['user_id'], unique=False)

    op.create_table('aml_organisation_profiles',
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.BigInteger(), nullable=False),
    sa.Column('is_pep', sa.Boolean(), nullable=False),
    sa.Column('pep_details', sa.JSON(), nullable=True),
    sa.Column('ubo_json', sa.JSON(), nullable=True),
    sa.Column('nin', sa.String(length=120), nullable=True),
    sa.Column('ursb_registration', sa.String(length=120), nullable=True),
    sa.Column('edd_status', sa.String(length=20), nullable=False),
    sa.Column('edd_rationale', sa.Text(), nullable=True),
    sa.Column('edd_approved_by', sa.BigInteger(), nullable=True),
    sa.Column('edd_approved_at', sa.DateTime(), nullable=True),
    sa.Column('screening_result_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("edd_status IN ('not_required','required','in_progress','completed')", name='ck_org_aml_edd_status'),
    sa.ForeignKeyConstraint(['edd_approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['screening_result_id'], ['aml_screening_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aml_organisation_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aml_organisation_profiles_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_aml_organisation_profiles_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_aml_organisation_profiles_organisation_id'), ['organisation_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_aml_organisation_profiles_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_aml_organisation_profiles_screening_result_id'), ['screening_result_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_aml_organisation_profiles_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aml_organisation_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aml_organisation_profiles_updated_at'))
        batch_op.drop_index(batch_op.f('ix_aml_organisation_profiles_screening_result_id'))
        batch_op.drop_index(batch_op.f('ix_aml_organisation_profiles_public_id'))
        batch_op.drop_index(batch_op.f('ix_aml_organisation_profiles_organisation_id'))
        batch_op.drop_index(batch_op.f('ix_aml_organisation_profiles_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_aml_organisation_profiles_created_at'))

    op.drop_table('aml_organisation_profiles')
    with op.batch_alter_table('aml_ctr_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aml_ctr_alerts_user_id'))
        batch_op.drop_index(batch_op.f('ix_aml_ctr_alerts_updated_at'))
        batch_op.drop_index(batch_op.f('ix_aml_ctr_alerts_status'))
        batch_op.drop_index(batch_op.f('ix_aml_ctr_alerts_public_id'))
        batch_op.drop_index(batch_op.f('ix_aml_ctr_alerts_period_date'))
        batch_op.drop_index(batch_op.f('ix_aml_ctr_alerts_jurisdiction_id'))
        batch_op.drop_index(batch_op.f('ix_aml_ctr_alerts_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_aml_ctr_alerts_created_at'))
        batch_op.drop_index(batch_op.f('ix_aml_ctr_alerts_alert_type'))

    op.drop_table('aml_ctr_alerts')
    with op.batch_alter_table('aml_backtest_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aml_backtest_runs_updated_at'))
        batch_op.drop_index(batch_op.f('ix_aml_backtest_runs_scenario_id'))
        batch_op.drop_index(batch_op.f('ix_aml_backtest_runs_public_id'))
        batch_op.drop_index(batch_op.f('ix_aml_backtest_runs_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_aml_backtest_runs_created_at'))

    op.drop_table('aml_backtest_runs')
    with op.batch_alter_table('fraud_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fraud_alerts_user_id'))
        batch_op.drop_index(batch_op.f('ix_fraud_alerts_transaction_id'))
        batch_op.drop_index('ix_fraud_alert_user_id')
        batch_op.drop_index('ix_fraud_alert_transaction_id')
        batch_op.drop_index('ix_fraud_alert_status')
        batch_op.drop_index('ix_fraud_alert_risk_score')
        batch_op.drop_index('ix_fraud_alert_created_at')

    op.drop_table('fraud_alerts')
    with op.batch_alter_table('aml_transaction_monitor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aml_transaction_monitor_user_id'))
        batch_op.drop_index(batch_op.f('ix_aml_transaction_monitor_updated_at'))
        batch_op.drop_index(batch_op.f('ix_aml_transaction_monitor_monitoring_date'))
        batch_op.drop_index(batch_op.f('ix_aml_transaction_monitor_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_aml_transaction_monitor_created_at'))

    op.drop_table('aml_transaction_monitor')
    with op.batch_alter_table('aml_training_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aml_training_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_aml_training_records_updated_at'))
        batch_op.drop_index(batch_op.f('ix_aml_training_records_public_id'))
        batch_op.drop_index(batch_op.f('ix_aml_training_records_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_aml_training_records_created_at'))

    op.drop_table('aml_training_records')
    with op.batch_alter_table('aml_terminated_entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aml_terminated_entities_updated_at'))
        batch_op.drop_index(batch_op.f('ix_aml_terminated_entities_registration_number'))
        batch_op.drop_index(batch_op.f('ix_aml_terminated_entities_public_id'))
        batch_op.drop_index(batch_op.f('ix_aml_terminated_entities_national_id'))
        batch_op.drop_index(batch_op.f('ix_aml_terminated_entities_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_aml_terminated_entities_created_at'))

    op.drop_table('aml_terminated_entities')
    with op.batch_alter_table('aml_screening_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aml_screening_results_user_id'))
        batch_op.drop_index(batch_op.f('ix_aml_screening_results_updated_at'))
        batch_op.drop_index(batch_op.f('ix_aml_screening_results_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_aml_screening_results_risk_level'))
        batch_op.drop_index(batch_op.f('ix_aml_screening_results_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_aml_screening_results_created_at'))

    op.drop_table('aml_screening_results')
    with op.batch_alter_table('aml_retention_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aml_retention_policies_updated_at'))
        batch_op.drop_index(batch_op.f('ix_aml_retention_policies_public_id'))
        batch_op.drop_index(batch_op.f('ix_aml_retention_policies_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_aml_retention_policies_created_at'))

    op.drop_table('aml_retention_policies')
    with op.batch_alter_table('aml_regulatory_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aml_regulatory_reports_updated_at'))
        batch_op.drop_index(batch_op.f('ix_aml_regulatory_reports_subject_user_id'))
        batch_op.drop_index(batch_op.f('ix_aml_regulatory_reports_subject_org_id'))
        batch_op.drop_index(batch_op.f('ix_aml_regulatory_reports_status'))
        batch_op.drop_index(batch_op.f('ix_aml_regulatory_reports_report_type'))
        batch_op.drop_index(batch_op.f('ix_aml_regulatory_reports_report_number'))
        batch_op.drop_index(batch_op.f('ix_aml_regulatory_reports_related_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_aml_regulatory_reports_public_id'))
        batch_op.drop_index(batch_op.f('ix_aml_regulatory_reports_jurisdiction_id'))
        batch_op.drop_index(batch_op.f('ix_aml_regulatory_reports_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_aml_regulatory_reports_due_at'))
        batch_op.drop_index(batch_op.f('ix_aml_regulatory_reports_created_at'))

    op.drop_table('aml_regulatory_reports')
    with op.batch_alter_table('aml_monitoring_scenarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aml_monitoring_scenarios_updated_at'))
        batch_op.drop_index(batch_op.f('ix_aml_monitoring_scenarios_public_id'))
        batch_op.drop_index(batch_op.f('ix_aml_monitoring_scenarios_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_aml_monitoring_scenarios_created_at'))

    op.drop_table('aml_monitoring_scenarios')
    with op.batch_alter_table('aml_attestations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aml_attestations_updated_at'))
        batch_op.drop_index(batch_op.f('ix_aml_attestations_public_id'))
        batch_op.drop_index(batch_op.f('ix_aml_attestations_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_aml_attestations_created_at'))
        batch_op.drop_index(batch_op.f('ix_aml_attestations_attested_by'))

    op.drop_table('aml_attestations')
    with op.batch_alter_table('aml_jurisdiction_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aml_jurisdiction_profiles_updated_at'))
        batch_op.drop_index(batch_op.f('ix_aml_jurisdiction_profiles_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_aml_jurisdiction_profiles_created_at'))
        batch_op.drop_index(batch_op.f('ix_aml_jurisdiction_profiles_country_code'))

    op.drop_table('aml_jurisdiction_profiles')
    # ### end Alembic commands ###
