"""Add published status to property lifecycle

Revision ID: 978aa0c43706
Revises: 0e5655df8acd
Create Date: 2026-07-25 02:15:36.419129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '978aa0c43706'
down_revision = '0e5655df8acd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_flags_risk_score'))
        batch_op.create_index('ix_content_flags_risk_score', ['risk_score', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_flags', schema=None) as batch_op:
        batch_op.drop_index('ix_content_flags_risk_score')
        batch_op.create_index(batch_op.f('ix_content_flags_risk_score'), ['risk_score'], unique=False)

    # ### end Alembic commands ###
