"""Add emergency access table

Revision ID: 9a90ef638142
Revises: 33109d1a4a4b
Create Date: 2026-05-06 14:25:10.660967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a90ef638142'
down_revision = '33109d1a4a4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emergency_access',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.Column('granted_to', sa.BigInteger(), nullable=False),
        sa.Column('granted_by', sa.BigInteger(), nullable=True),
        sa.Column('approved_by_secops', sa.BigInteger(), nullable=True),
        sa.Column('reason', sa.Text(), nullable=False),
        sa.Column('jira_ticket', sa.String(length=100), nullable=False),
        sa.Column('incident_type', sa.String(length=50), nullable=False),
        sa.Column('access_level', sa.String(length=50), nullable=False),
        sa.Column('allowed_actions', sa.JSON(), nullable=True),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.Column('started_at', sa.DateTime(), nullable=True),
        sa.Column('ended_at', sa.DateTime(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('is_used', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['approved_by_secops'], ['users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['granted_to'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_access_active'), 'emergency_access', ['is_active'], unique=False)
    op.create_index(op.f('ix_emergency_access_expires_at'), 'emergency_access', ['expires_at'], unique=False)
    op.create_index(op.f('ix_emergency_access_granted_to'), 'emergency_access', ['granted_to'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emergency_access_granted_to'), table_name='emergency_access')
    op.drop_index(op.f('ix_emergency_access_expires_at'), table_name='emergency_access')
    op.drop_index(op.f('ix_emergency_access_active'), table_name='emergency_access')
    op.drop_table('emergency_access')
    # ### end Alembic commands ###
