"""audit schema differences

Revision ID: 9f75675b5e52
Revises: 20260902_2255
Create Date: 2026-09-05 01:39:16.405717

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9f75675b5e52'
down_revision = '20260902_2255'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transport_passengers',
    sa.Column('public_id', sa.String(length=64), nullable=False),
    sa.Column('booking_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('assigned_vehicle_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('seat_label', sa.String(length=20), nullable=True),
    sa.Column('claim_token_hash', sa.String(length=128), nullable=True),
    sa.Column('claim_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claim_token_consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claimed_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('passenger_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_vehicle_id'], ['transport_vehicles.id'], name='fk_tp_vehicle', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['booking_id'], ['transport_bookings.id'], name='fk_tp_booking', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['claimed_by_user_id'], ['users.id'], name='fk_tp_claimed_by', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_tp_user', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transport_passengers', schema=None) as batch_op:
        batch_op.create_index('ix_tp_booking', ['booking_id', 'status'], unique=False)
        batch_op.create_index('ix_tp_claim_hash', ['claim_token_hash'], unique=True)
        batch_op.create_index('ix_tp_user', ['user_id', 'status'], unique=False)
        batch_op.create_index('ix_tp_vehicle', ['assigned_vehicle_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_transport_passengers_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transport_passengers_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_transport_passengers_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_transport_passengers_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transport_passengers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transport_passengers_updated_at'))
        batch_op.drop_index(batch_op.f('ix_transport_passengers_public_id'))
        batch_op.drop_index(batch_op.f('ix_transport_passengers_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_transport_passengers_created_at'))
        batch_op.drop_index('ix_tp_vehicle')
        batch_op.drop_index('ix_tp_user')
        batch_op.drop_index('ix_tp_claim_hash')
        batch_op.drop_index('ix_tp_booking')

    op.drop_table('transport_passengers')
    # ### end Alembic commands ###
