"""add_fan_fields_to_user_profile

Revision ID: a73a4f5c63aa
Revises: af20cf39283a
Create Date: 2026-05-06 09:22:39.647263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a73a4f5c63aa'
down_revision = 'af20cf39283a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile_audit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attempted_at', sa.DateTime(), nullable=False))

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fan_team', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('display_name', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_profiles_fan_team'), ['fan_team'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_profiles_fan_team'))
        batch_op.drop_column('bio')
        batch_op.drop_column('avatar_url')
        batch_op.drop_column('display_name')
        batch_op.drop_column('fan_team')

    with op.batch_alter_table('user_profile_audit', schema=None) as batch_op:
        batch_op.drop_column('attempted_at')

    # ### end Alembic commands ###
