"""add_booking_idempotency_key

Revision ID: aab3e38879dc
Revises: 6f8f4c204b61
Create Date: 2026-09-22 18:33:53.346046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aab3e38879dc'
down_revision = '6f8f4c204b61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisation_payment_gateways',
    sa.Column('organisation_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.Enum('FLUTTERWAVE', 'PAYSTACK', 'MTN_MOMO', 'AIRTEL_MONEY', 'VISA', 'MASTERCARD', 'PAYPAL', 'ALIPAY', 'WECHAT_PAY', 'BANK_TRANSFER', 'STRIPE', 'MPESA', name='payment_gateway_provider'), nullable=False),
    sa.Column('environment', sa.Enum('SANDBOX', 'PRODUCTION', name='gateway_environment'), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('api_key', sa.String(length=255), nullable=True),
    sa.Column('api_secret', sa.String(length=255), nullable=True),
    sa.Column('merchant_id', sa.String(length=100), nullable=True),
    sa.Column('webhook_url', sa.String(length=500), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('supported_currencies', sa.JSON(), nullable=True),
    sa.Column('min_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('transaction_fee', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('fee_currency', sa.String(length=3), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('last_tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_test_result', sa.String(length=20), nullable=True),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisation_id', 'provider', name='uq_org_gateway_provider')
    )
    with op.batch_alter_table('organisation_payment_gateways', schema=None) as batch_op:
        batch_op.create_index('ix_org_gateway_org_active', ['organisation_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_organisation_payment_gateways_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_organisation_payment_gateways_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_organisation_payment_gateways_organisation_id'), ['organisation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organisation_payment_gateways_updated_at'), ['updated_at'], unique=False)

    with op.batch_alter_table('transport_bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idempotency_key', sa.String(length=128), nullable=True))
        batch_op.create_index('ix_booking_idem', ['idempotency_key'], unique=True, postgresql_where=sa.text('idempotency_key IS NOT NULL'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transport_bookings', schema=None) as batch_op:
        batch_op.drop_index('ix_booking_idem', postgresql_where=sa.text('idempotency_key IS NOT NULL'))
        batch_op.drop_column('idempotency_key')

    with op.batch_alter_table('organisation_payment_gateways', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organisation_payment_gateways_updated_at'))
        batch_op.drop_index(batch_op.f('ix_organisation_payment_gateways_organisation_id'))
        batch_op.drop_index(batch_op.f('ix_organisation_payment_gateways_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_organisation_payment_gateways_created_at'))
        batch_op.drop_index('ix_org_gateway_org_active')

    op.drop_table('organisation_payment_gateways')
    # ### end Alembic commands ###
