"""add accommodation room holds

Revision ID: acf73a88632f
Revises: f312046d12e8
Create Date: 2026-07-31 18:06:08.315290

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'acf73a88632f'
down_revision = 'f312046d12e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accommodation_booking_status_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('booking_id', sa.BigInteger(), nullable=False),
    sa.Column('from_status', sa.String(length=50), nullable=True),
    sa.Column('to_status', sa.String(length=50), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('changed_by', sa.BigInteger(), nullable=True),
    sa.Column('trigger', sa.String(length=100), nullable=True),
    sa.Column('change_metadata', sa.JSON(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['accommodation_bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accommodation_booking_status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accommodation_booking_status_history_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_booking_status_history_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_booking_status_history_updated_at'), ['updated_at'], unique=False)

    with op.batch_alter_table('accommodation_booking_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_history_booking'))
        batch_op.drop_index(batch_op.f('idx_history_timestamp'))
        batch_op.drop_index(batch_op.f('ix_accommodation_booking_history_booking_id'))
        batch_op.drop_index(batch_op.f('ix_accommodation_booking_history_created_at'))
        batch_op.drop_index(batch_op.f('ix_accommodation_booking_history_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_accommodation_booking_history_updated_at'))

    op.drop_table('accommodation_booking_history')
    with op.batch_alter_table('user_nonces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_nonces_nonce'))
        batch_op.create_index(batch_op.f('ix_user_nonces_nonce'), ['nonce'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_nonces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_nonces_nonce'))
        batch_op.create_index(batch_op.f('ix_user_nonces_nonce'), ['nonce'], unique=False)

    op.create_table('accommodation_booking_history',
    sa.Column('booking_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('from_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('to_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('changed_by_user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('changed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['accommodation_bookings.id'], name=op.f('accommodation_booking_history_booking_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], name=op.f('accommodation_booking_history_changed_by_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('accommodation_booking_history_pkey'))
    )
    with op.batch_alter_table('accommodation_booking_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accommodation_booking_history_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_booking_history_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_booking_history_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_booking_history_booking_id'), ['booking_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_history_timestamp'), ['changed_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_history_booking'), ['booking_id'], unique=False)

    with op.batch_alter_table('accommodation_booking_status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accommodation_booking_status_history_updated_at'))
        batch_op.drop_index(batch_op.f('ix_accommodation_booking_status_history_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_accommodation_booking_status_history_created_at'))

    op.drop_table('accommodation_booking_status_history')
    # ### end Alembic commands ###
