"""sync onboarding models

Revision ID: af20cf39283a
Revises: e9c505703ce2
Create Date: 2026-05-05 01:27:47.236633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af20cf39283a'
down_revision = 'e9c505703ce2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
