"""Add email_verified, phone_verified, and security fields to User model

Revision ID: b512872ef96a
Revises: 8e254b19689d
Create Date: 2026-04-15 19:07:12.981902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b512872ef96a'
down_revision = '8e254b19689d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=64), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('phone_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('security_question', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('security_answer_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('recovery_code', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('recovery_code')
        batch_op.drop_column('security_answer_hash')
        batch_op.drop_column('security_question')
        batch_op.drop_column('phone_verified')
        batch_op.drop_column('email_verified')

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('country')
        batch_op.drop_column('city')

    # ### end Alembic commands ###
