"""add security deposit columns to bookings

Revision ID: b8f317d76694
Revises: 396efe6667ff
Create Date: 2026-08-02 20:58:14.824510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8f317d76694'
down_revision = '396efe6667ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accommodation_bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('security_deposit_amount', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('security_deposit_held', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('security_deposit_released_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('aggregators', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aggregators_api_key'))
        batch_op.create_index('ix_aggregators_api_key', ['api_key'], unique=False)

    with op.batch_alter_table('content_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_flags_risk_score'))
        batch_op.create_index('ix_content_flags_risk_score', ['risk_score', 'status'], unique=False)

    with op.batch_alter_table('user_nonces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_nonces_nonce'))
        batch_op.create_index(batch_op.f('ix_user_nonces_nonce'), ['nonce'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_nonces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_nonces_nonce'))
        batch_op.create_index(batch_op.f('ix_user_nonces_nonce'), ['nonce'], unique=False)

    with op.batch_alter_table('content_flags', schema=None) as batch_op:
        batch_op.drop_index('ix_content_flags_risk_score')
        batch_op.create_index(batch_op.f('ix_content_flags_risk_score'), ['risk_score'], unique=False)

    with op.batch_alter_table('aggregators', schema=None) as batch_op:
        batch_op.drop_index('ix_aggregators_api_key')
        batch_op.create_index(batch_op.f('ix_aggregators_api_key'), ['api_key'], unique=True)

    with op.batch_alter_table('accommodation_bookings', schema=None) as batch_op:
        batch_op.drop_column('security_deposit_released_at')
        batch_op.drop_column('security_deposit_held')
        batch_op.drop_column('security_deposit_amount')

    # ### end Alembic commands ###
