"""convert accommodation enums to strings

Revision ID: ba262522c43c
Revises: d95160fba1fd
Create Date: 2026-07-18 09:44:06.262240

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ba262522c43c'
down_revision = 'd95160fba1fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accommodation_room_categories',
    sa.Column('property_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('short_code', sa.String(length=20), nullable=True),
    sa.Column('max_guests', sa.Integer(), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('beds', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('base_price_per_night', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('cleaning_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('base_price_per_night >= 0', name='ck_category_price_positive'),
    sa.CheckConstraint('max_guests >= 1', name='ck_category_guests_min'),
    sa.ForeignKeyConstraint(['property_id'], ['accommodation_properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'name', name='uq_category_per_property')
    )
    with op.batch_alter_table('accommodation_room_categories', schema=None) as batch_op:
        batch_op.create_index('idx_room_category_active', ['is_active'], unique=False)
        batch_op.create_index('idx_room_category_property', ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_room_categories_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_room_categories_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_room_categories_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_room_categories_updated_at'), ['updated_at'], unique=False)

    op.create_table('accommodation_rooms',
    sa.Column('property_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('room_number', sa.String(length=20), nullable=False),
    sa.Column('floor', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_maintenance', sa.Boolean(), nullable=False),
    sa.Column('maintenance_reason', sa.Text(), nullable=True),
    sa.Column('maintenance_start', sa.DateTime(), nullable=True),
    sa.Column('maintenance_end', sa.DateTime(), nullable=True),
    sa.Column('features_override', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['accommodation_room_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['property_id'], ['accommodation_properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'room_number', name='uq_room_number_per_property')
    )
    with op.batch_alter_table('accommodation_rooms', schema=None) as batch_op:
        batch_op.create_index('idx_room_category', ['category_id'], unique=False)
        batch_op.create_index('idx_room_property', ['property_id'], unique=False)
        batch_op.create_index('idx_room_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_rooms_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_rooms_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_rooms_updated_at'), ['updated_at'], unique=False)

    op.create_table('accommodation_room_bookings',
    sa.Column('booking_id', sa.BigInteger(), nullable=False),
    sa.Column('room_id', sa.BigInteger(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('assigned_by', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['booking_id'], ['accommodation_bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['accommodation_rooms.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id', 'room_id', name='uq_room_booking_unique')
    )
    with op.batch_alter_table('accommodation_room_bookings', schema=None) as batch_op:
        batch_op.create_index('idx_room_booking_booking', ['booking_id'], unique=False)
        batch_op.create_index('idx_room_booking_room', ['room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_room_bookings_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_room_bookings_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_room_bookings_updated_at'), ['updated_at'], unique=False)

    with op.batch_alter_table('system_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_configs_created_at'))
        batch_op.drop_index(batch_op.f('ix_system_configs_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_system_configs_key'))
        batch_op.drop_index(batch_op.f('ix_system_configs_updated_at'))

    op.drop_table('system_configs')
    with op.batch_alter_table('accommodation_blocked_dates', schema=None) as batch_op:
        batch_op.alter_column('reason',
               existing_type=postgresql.ENUM('BOOKED', 'TEMPORARY_HOLD', 'OWNER_BLOCKED', 'MAINTENANCE', 'SEASONAL', 'temporary_hold', name='accommodationblockedreason'),
               type_=sa.String(length=50),
               existing_nullable=False)

    with op.batch_alter_table('accommodation_bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_room_id', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('checked_in_by', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('checked_out_by', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('is_checked_in', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('is_checked_out', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.create_index(batch_op.f('ix_accommodation_bookings_assigned_room_id'), ['assigned_room_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['checked_in_by'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['checked_out_by'], ['id'])
        batch_op.create_foreign_key(None, 'accommodation_rooms', ['assigned_room_id'], ['id'])

    with op.batch_alter_table('accommodation_inventory_blocks', schema=None) as batch_op:
        batch_op.alter_column('reason',
               existing_type=postgresql.ENUM('MAINTENANCE', 'RENOVATION', 'SEASONAL_CLOSE', 'OWNER_BLOCK', name='inventory_block_reason_enum'),
               type_=sa.String(length=50),
               existing_nullable=False)

    with op.batch_alter_table('accommodation_properties', schema=None) as batch_op:
        batch_op.alter_column('property_type',
               existing_type=postgresql.ENUM('ENTIRE_PLACE', 'PRIVATE_ROOM', 'SHARED_ROOM', 'HOTEL_ROOM', name='accommodationpropertytype'),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('cancellation_policy',
               existing_type=postgresql.ENUM('FLEXIBLE', 'MODERATE', 'STRICT', 'SUPER_STRICT', name='accommodationcancellationpolicy'),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('DRAFT', 'PENDING_REVIEW', 'ACTIVE', 'SUSPENDED', 'ARCHIVED', name='accommodationpropertystatus'),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('verification_status',
               existing_type=postgresql.ENUM('UNVERIFIED', 'PENDING', 'VERIFIED', 'REJECTED', name='accommodationverificationstatus'),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('accommodation_reviews', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', 'FLAGGED', name='accommodationreviewstatus'),
               type_=sa.String(length=50),
               existing_nullable=False)

    with op.batch_alter_table('content_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_flags_risk_score'))
        batch_op.create_index(batch_op.f('ix_content_flags_risk_score'), ['risk_score'], unique=False)

    # ==========================================
    # FIX EXISTING DATA (lowercase enum values)
    # ==========================================
    op.execute("UPDATE accommodation_properties SET status = LOWER(status), property_type = LOWER(property_type), cancellation_policy = LOWER(cancellation_policy), verification_status = LOWER(verification_status)")
    op.execute("UPDATE accommodation_reviews SET status = LOWER(status)")
    op.execute("UPDATE accommodation_blocked_dates SET reason = LOWER(reason)")
    op.execute("UPDATE accommodation_inventory_blocks SET reason = LOWER(reason)")

    # ==========================================
    # ADD CHECK CONSTRAINTS (Manual addition)
    # ==========================================
    
    # Property status check
    op.create_check_constraint(
        'ck_property_status_valid',
        'accommodation_properties',
        "status IN ('draft', 'pending_review', 'active', 'suspended', 'archived')"
    )
    
    # Property type check
    op.create_check_constraint(
        'ck_property_type_valid',
        'accommodation_properties',
        "property_type IN ('entire_place', 'private_room', 'shared_room', 'hotel_room', 'community_host')"
    )
    
    # Cancellation policy check
    op.create_check_constraint(
        'ck_cancellation_policy_valid',
        'accommodation_properties',
        "cancellation_policy IN ('flexible', 'moderate', 'strict', 'super_strict')"
    )
    
    # Verification status check
    op.create_check_constraint(
        'ck_verification_status_valid',
        'accommodation_properties',
        "verification_status IN ('unverified', 'pending', 'verified', 'rejected')"
    )
    
    # Review status check
    op.create_check_constraint(
        'ck_review_status_valid',
        'accommodation_reviews',
        "status IN ('pending', 'approved', 'rejected', 'flagged')"
    )
    
    # Blocked date reason check
    op.create_check_constraint(
        'ck_blocked_reason_valid',
        'accommodation_blocked_dates',
        "reason IN ('booked', 'temporary_hold', 'owner_blocked', 'maintenance', 'seasonal')"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_flags_risk_score'))
        batch_op.create_index(batch_op.f('ix_content_flags_risk_score'), ['risk_score', 'status'], unique=False)

    with op.batch_alter_table('accommodation_reviews', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', 'FLAGGED', name='accommodationreviewstatus'),
               existing_nullable=False)

    with op.batch_alter_table('accommodation_properties', schema=None) as batch_op:
        batch_op.alter_column('verification_status',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('UNVERIFIED', 'PENDING', 'VERIFIED', 'REJECTED', name='accommodationverificationstatus'),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('DRAFT', 'PENDING_REVIEW', 'ACTIVE', 'SUSPENDED', 'ARCHIVED', name='accommodationpropertystatus'),
               existing_nullable=False)
        batch_op.alter_column('cancellation_policy',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('FLEXIBLE', 'MODERATE', 'STRICT', 'SUPER_STRICT', name='accommodationcancellationpolicy'),
               existing_nullable=True)
        batch_op.alter_column('property_type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('ENTIRE_PLACE', 'PRIVATE_ROOM', 'SHARED_ROOM', 'HOTEL_ROOM', name='accommodationpropertytype'),
               existing_nullable=False)

    with op.batch_alter_table('accommodation_inventory_blocks', schema=None) as batch_op:
        batch_op.alter_column('reason',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('MAINTENANCE', 'RENOVATION', 'SEASONAL_CLOSE', 'OWNER_BLOCK', name='inventory_block_reason_enum'),
               existing_nullable=False)

    with op.batch_alter_table('accommodation_bookings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_accommodation_bookings_assigned_room_id'))
        batch_op.drop_column('is_checked_out')
        batch_op.drop_column('is_checked_in')
        batch_op.drop_column('checked_out_by')
        batch_op.drop_column('checked_in_by')
        batch_op.drop_column('assigned_room_id')

    with op.batch_alter_table('accommodation_blocked_dates', schema=None) as batch_op:
        batch_op.alter_column('reason',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('BOOKED', 'TEMPORARY_HOLD', 'OWNER_BLOCKED', 'MAINTENANCE', 'SEASONAL', 'temporary_hold', name='accommodationblockedreason'),
               existing_nullable=False)

    op.create_table('system_configs',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('system_configs_created_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('system_configs_pkey')),
    sa.UniqueConstraint('key', name=op.f('uq_system_configs_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('system_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_configs_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_configs_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_configs_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_configs_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('accommodation_room_bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accommodation_room_bookings_updated_at'))
        batch_op.drop_index(batch_op.f('ix_accommodation_room_bookings_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_accommodation_room_bookings_created_at'))
        batch_op.drop_index('idx_room_booking_room')
        batch_op.drop_index('idx_room_booking_booking')

    op.drop_table('accommodation_room_bookings')
    with op.batch_alter_table('accommodation_rooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accommodation_rooms_updated_at'))
        batch_op.drop_index(batch_op.f('ix_accommodation_rooms_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_accommodation_rooms_created_at'))
        batch_op.drop_index('idx_room_status')
        batch_op.drop_index('idx_room_property')
        batch_op.drop_index('idx_room_category')

    op.drop_table('accommodation_rooms')
    with op.batch_alter_table('accommodation_room_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accommodation_room_categories_updated_at'))
        batch_op.drop_index(batch_op.f('ix_accommodation_room_categories_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_accommodation_room_categories_is_active'))
        batch_op.drop_index(batch_op.f('ix_accommodation_room_categories_created_at'))
        batch_op.drop_index('idx_room_category_property')
        batch_op.drop_index('idx_room_category_active')

    op.drop_table('accommodation_room_categories')
    # ### end Alembic commands ###
