"""add created_by to inventory_blocks

Revision ID: bcf13cf9d185
Revises: 2499ed67dc8c
Create Date: 2026-08-08 23:02:11.292035

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bcf13cf9d185'
down_revision = '2499ed67dc8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE auth_configurations SET otp_channels = '\"email\"' WHERE otp_channels IS NULL")
    op.execute("UPDATE auth_configurations SET email_verification_required_for = '[]' WHERE email_verification_required_for IS NULL")
    
    with op.batch_alter_table('accommodation_inventory_blocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.BigInteger(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('auth_configurations', schema=None) as batch_op:
        batch_op.alter_column('otp_channels',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               server_default='\"email\"')
        batch_op.alter_column('email_verification_required_for',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               server_default='[]')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_configurations', schema=None) as batch_op:
        batch_op.alter_column('email_verification_required_for',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
        batch_op.alter_column('otp_channels',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)

    with op.batch_alter_table('accommodation_inventory_blocks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
