"""add accommodation_complaint_opened to notifications type constraint

Revision ID: c0758a81e4b0
Revises: 882868e0250b
Create Date: 2026-08-12 20:42:16.700138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0758a81e4b0'
down_revision = '882868e0250b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accommodation_booking_price_adjustments',
    sa.Column('booking_id', sa.BigInteger(), nullable=False),
    sa.Column('adjustment_type', sa.String(length=50), nullable=False),
    sa.Column('old_check_in', sa.Date(), nullable=True),
    sa.Column('old_check_out', sa.Date(), nullable=True),
    sa.Column('new_check_in', sa.Date(), nullable=True),
    sa.Column('new_check_out', sa.Date(), nullable=True),
    sa.Column('old_num_nights', sa.Integer(), nullable=True),
    sa.Column('new_num_nights', sa.Integer(), nullable=False),
    sa.Column('old_total_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('new_total_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('old_nightly_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('delta_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('old_amount_paid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('new_amount_due', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('refund_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('notify_guest', sa.Boolean(), nullable=False),
    sa.Column('payment_processed', sa.Boolean(), nullable=False),
    sa.Column('changed_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('adjustment_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("adjustment_type IN ('date_modification', 'early_checkout', 'late_checkin')", name='ck_price_adj_type_valid'),
    sa.CheckConstraint('new_num_nights >= 0', name='ck_price_adj_new_nights_positive'),
    sa.ForeignKeyConstraint(['booking_id'], ['accommodation_bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accommodation_booking_price_adjustments', schema=None) as batch_op:
        batch_op.create_index('idx_price_adj_booking', ['booking_id'], unique=False)
        batch_op.create_index('idx_price_adj_created', ['created_at'], unique=False)
        batch_op.create_index('idx_price_adj_type', ['adjustment_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_booking_price_adjustments_booking_id'), ['booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_booking_price_adjustments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_booking_price_adjustments_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_booking_price_adjustments_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accommodation_booking_price_adjustments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accommodation_booking_price_adjustments_updated_at'))
        batch_op.drop_index(batch_op.f('ix_accommodation_booking_price_adjustments_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_accommodation_booking_price_adjustments_created_at'))
        batch_op.drop_index(batch_op.f('ix_accommodation_booking_price_adjustments_booking_id'))
        batch_op.drop_index('idx_price_adj_type')
        batch_op.drop_index('idx_price_adj_created')
        batch_op.drop_index('idx_price_adj_booking')

    op.drop_table('accommodation_booking_price_adjustments')
    # ### end Alembic commands ###
