"""Sync schema: remove fan_profiles and add missing foreign keys

Revision ID: c76f972a4ed1
Revises: 67a805678c79
Create Date: 2026-04-14 00:16:24.407677

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c76f972a4ed1'
down_revision = '67a805678c79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fan_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fan_profiles_created_at'))
        batch_op.drop_index(batch_op.f('ix_fan_profiles_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_fan_profiles_updated_at'))
        batch_op.drop_index(batch_op.f('ix_fan_profiles_user_id'))

    op.drop_table('fan_profiles')
    with op.batch_alter_table('organisations', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_orgs_primary_contact_user_id', 'users', ['primary_contact_user_id'], ['id'], ondelete='SET NULL', use_alter=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_users_default_org_id', 'organisations', ['default_org_id'], ['id'], ondelete='SET NULL', use_alter=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_default_org_id', type_='foreignkey')

    with op.batch_alter_table('organisations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_orgs_primary_contact_user_id', type_='foreignkey')

    op.create_table('fan_profiles',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('nationality', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('favorite_team', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('avatar_url', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('bio', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('verification_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fan_profiles_user_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verification_id'], ['individual_verifications.id'], name=op.f('fan_profiles_verification_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('fan_profiles_pkey'))
    )
    with op.batch_alter_table('fan_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fan_profiles_user_id'), ['user_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_fan_profiles_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_fan_profiles_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_fan_profiles_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###
