"""Update ContentFlag model with enterprise features

Revision ID: ceadd442d369
Revises: dc216edcf743
Create Date: 2026-05-08 14:16:40.222477

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ceadd442d369'
down_revision = 'dc216edcf743'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Only update ContentFlag indexes for enterprise features
    with op.batch_alter_table('content_flags', schema=None) as batch_op:
        # Drop the old composite index and create individual indexes
        batch_op.drop_index(batch_op.f('ix_content_flags_risk_score'))
        batch_op.create_index(batch_op.f('ix_content_flags_risk_score'), ['risk_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_flags_assigned_to'), ['assigned_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_flags_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_flags_content_type'), ['content_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_flags_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_flags_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_flags_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_flags_flagged_by'), ['flagged_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_flags_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_flags_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_flags_sla_due_at'), ['sla_due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_flags_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Only revert ContentFlag index changes
    with op.batch_alter_table('content_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_flags_status'))
        batch_op.drop_index(batch_op.f('ix_content_flags_sla_due_at'))
        batch_op.drop_index(batch_op.f('ix_content_flags_priority'))
        batch_op.drop_index(batch_op.f('ix_content_flags_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_content_flags_flagged_by'))
        batch_op.drop_index(batch_op.f('ix_content_flags_entity_type'))
        batch_op.drop_index(batch_op.f('ix_content_flags_entity_id'))
        batch_op.drop_index(batch_op.f('ix_content_flags_created_at'))
        batch_op.drop_index(batch_op.f('ix_content_flags_content_type'))
        batch_op.drop_index(batch_op.f('ix_content_flags_category'))
        batch_op.drop_index(batch_op.f('ix_content_flags_assigned_to'))
        batch_op.drop_index(batch_op.f('ix_content_flags_risk_score'))
        batch_op.create_index(batch_op.f('ix_content_flags_risk_score'), ['risk_score', 'status'], unique=False)

    # ### end Alembic commands ###
