"""drop_fan_profiles_table

Revision ID: e7c5932521a3
Revises: a73a4f5c63aa
Create Date: 2026-05-06 13:15:45.785419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7c5932521a3'
down_revision = 'a73a4f5c63aa'
branch_labels = None
depends_on = None


def upgrade():
    op.drop_table('fan_profiles')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
