"""make wallet admin events datetimes timezone-aware

Revision ID: ed6307401623
Revises: 2fa5d406a740
Create Date: 2026-07-18 13:19:01.632451

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ed6307401623'
down_revision = '2fa5d406a740'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_commissions', schema=None) as batch_op:
        batch_op.alter_column('paid_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,

                postgresql_using="paid_at AT TIME ZONE 'Africa/Nairobi'"

        )

    with op.batch_alter_table('content_flags', schema=None) as batch_op:
        batch_op.alter_column('resolved_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,

                postgresql_using="resolved_at AT TIME ZONE 'Africa/Nairobi'"

        )
        batch_op.alter_column('sla_due_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,

                postgresql_using="sla_due_at AT TIME ZONE 'Africa/Nairobi'"

        )
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
                existing_server_default=sa.text('now()'),
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'"

        )


        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
                existing_server_default=sa.text('now()'),
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'"

        )


        batch_op.alter_column('referred_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,

                postgresql_using="referred_at AT TIME ZONE 'Africa/Nairobi'"

        )
        batch_op.drop_index(batch_op.f('ix_content_flags_risk_score'))

        batch_op.create_index('ix_content_flags_risk_score', ['risk_score', 'status'], unique=False)

    with op.batch_alter_table('content_submissions', schema=None) as batch_op:
        batch_op.alter_column('reviewed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,

                postgresql_using="reviewed_at AT TIME ZONE 'Africa/Nairobi'"

        )
        batch_op.alter_column('claimed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,

                postgresql_using="claimed_at AT TIME ZONE 'Africa/Nairobi'"

        )
        batch_op.alter_column('resolved_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,

                postgresql_using="resolved_at AT TIME ZONE 'Africa/Nairobi'"

        )
        batch_op.alter_column('sla_due_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,

                postgresql_using="sla_due_at AT TIME ZONE 'Africa/Nairobi'"

        )

    with op.batch_alter_table('discount_codes', schema=None) as batch_op:
        batch_op.alter_column('valid_from',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,

                postgresql_using="valid_from AT TIME ZONE 'Africa/Nairobi'"

        )
        batch_op.alter_column('valid_until',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,

                postgresql_using="valid_until AT TIME ZONE 'Africa/Nairobi'"

        )

    with op.batch_alter_table('emergency_access', schema=None) as batch_op:
        batch_op.alter_column('expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,

                postgresql_using="expires_at AT TIME ZONE 'Africa/Nairobi'"

        )
        batch_op.alter_column('started_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,

                postgresql_using="started_at AT TIME ZONE 'Africa/Nairobi'"

        )
        batch_op.alter_column('ended_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,

                postgresql_using="ended_at AT TIME ZONE 'Africa/Nairobi'"

        )

    with op.batch_alter_table('event_assignments', schema=None) as batch_op:
        batch_op.alter_column('assigned_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,

                postgresql_using="assigned_at AT TIME ZONE 'Africa/Nairobi'"

        )

    with op.batch_alter_table('event_host_registrations', schema=None) as batch_op:
        batch_op.alter_column('registered_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,

                postgresql_using="registered_at AT TIME ZONE 'Africa/Nairobi'"

        )
        batch_op.alter_column('approved_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,

                postgresql_using="approved_at AT TIME ZONE 'Africa/Nairobi'"

        )
        batch_op.alter_column('rejected_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,

                postgresql_using="rejected_at AT TIME ZONE 'Africa/Nairobi'"

        )

    with op.batch_alter_table('event_registrations', schema=None) as batch_op:
        batch_op.alter_column('checked_in_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,

                postgresql_using="checked_in_at AT TIME ZONE 'Africa/Nairobi'"

        )

    with op.batch_alter_table('event_roles', schema=None) as batch_op:
        batch_op.alter_column('assigned_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,

                postgresql_using="assigned_at AT TIME ZONE 'Africa/Nairobi'"

        )

    with op.batch_alter_table('event_ticket_types', schema=None) as batch_op:
        batch_op.alter_column('available_from',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,

                postgresql_using="available_from AT TIME ZONE 'Africa/Nairobi'"

        )
        batch_op.alter_column('available_until',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,

                postgresql_using="available_until AT TIME ZONE 'Africa/Nairobi'"

        )

    with op.batch_alter_table('event_transfer_logs', schema=None) as batch_op:
        batch_op.alter_column('transferred_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,

                postgresql_using="transferred_at AT TIME ZONE 'Africa/Nairobi'"

        )

    with op.batch_alter_table('event_transfer_requests', schema=None) as batch_op:
        batch_op.alter_column('approved_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,

                postgresql_using="approved_at AT TIME ZONE 'Africa/Nairobi'"

        )
        batch_op.alter_column('expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,

                postgresql_using="expires_at AT TIME ZONE 'Africa/Nairobi'"

        )

    with op.batch_alter_table('event_waitlist', schema=None) as batch_op:
        batch_op.alter_column('notified_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,

                postgresql_using="notified_at AT TIME ZONE 'Africa/Nairobi'"

        )
        batch_op.alter_column('converted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,

                postgresql_using="converted_at AT TIME ZONE 'Africa/Nairobi'"

        )

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('approved_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,

                postgresql_using="approved_at AT TIME ZONE 'Africa/Nairobi'"

        )
        batch_op.alter_column('rejected_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,

                postgresql_using="rejected_at AT TIME ZONE 'Africa/Nairobi'"

        )
        batch_op.alter_column('suspended_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,

                postgresql_using="suspended_at AT TIME ZONE 'Africa/Nairobi'"

        )
        batch_op.alter_column('deactivated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,

                postgresql_using="deactivated_at AT TIME ZONE 'Africa/Nairobi'"

        )
        batch_op.alter_column('taken_down_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,

                postgresql_using="taken_down_at AT TIME ZONE 'Africa/Nairobi'"

        )
        batch_op.alter_column('completed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,

                postgresql_using="completed_at AT TIME ZONE 'Africa/Nairobi'"

        )
        batch_op.alter_column('published_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,

                postgresql_using="published_at AT TIME ZONE 'Africa/Nairobi'"

        )

    with op.batch_alter_table('fx_rates', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,

                postgresql_using="timestamp AT TIME ZONE 'Africa/Nairobi'"

        )
        batch_op.alter_column('expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,

                postgresql_using="expires_at AT TIME ZONE 'Africa/Nairobi'"

        )

    with op.batch_alter_table('fx_transactions', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,

                postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'"

        )
        batch_op.alter_column('completed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,

                postgresql_using="completed_at AT TIME ZONE 'Africa/Nairobi'"

        )

    with op.batch_alter_table('moderation_logs', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,

                postgresql_using="timestamp AT TIME ZONE 'Africa/Nairobi'"

        )

    with op.batch_alter_table('payment_method_configs', schema=None) as batch_op:
        batch_op.alter_column('last_tested_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,

                postgresql_using="last_tested_at AT TIME ZONE 'Africa/Nairobi'"

        )

    with op.batch_alter_table('payment_provider_configs', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,

                postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'"

        )
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,

                postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'"

        )
        batch_op.alter_column('last_tested_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,

                postgresql_using="last_tested_at AT TIME ZONE 'Africa/Nairobi'"

        )

    with op.batch_alter_table('payout_requests', schema=None) as batch_op:
        batch_op.alter_column('approved_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,

                postgresql_using="approved_at AT TIME ZONE 'Africa/Nairobi'"

        )
        batch_op.alter_column('paid_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,

                postgresql_using="paid_at AT TIME ZONE 'Africa/Nairobi'"

        )

    with op.batch_alter_table('wallet_system_configs', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,

                postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'"

        )

    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.alter_column('next_retry_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,

                postgresql_using="next_retry_at AT TIME ZONE 'Africa/Nairobi'"

        )
        batch_op.alter_column('processed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,

                postgresql_using="processed_at AT TIME ZONE 'Africa/Nairobi'"

        )

    with op.batch_alter_table('agent_commissions', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('content_flags', schema=None) as batch_op:
        batch_op.alter_column('deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('content_submissions', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('discount_codes', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('emergency_access', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('event_assignments', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('event_host_registrations', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('event_moderation_logs', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('event_payment_preferences', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('event_registrations', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('event_roles', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('event_settings', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('event_themes', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('event_ticket_types', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('event_transfer_logs', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('event_transfer_requests', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('event_waitlist', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('moderation_logs', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('payment_method_configs', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('payout_requests', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('wallet_system_configs', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.alter_column('processed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,

                postgresql_using="processed_at AT TIME ZONE 'Africa/Nairobi'"

        )
        batch_op.alter_column('next_retry_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,

                postgresql_using="next_retry_at AT TIME ZONE 'Africa/Nairobi'"

        )

    with op.batch_alter_table('wallet_system_configs', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,

                postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'"

        )

    with op.batch_alter_table('payout_requests', schema=None) as batch_op:
        batch_op.alter_column('paid_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,

                postgresql_using="paid_at AT TIME ZONE 'Africa/Nairobi'"

        )
        batch_op.alter_column('approved_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,

                postgresql_using="approved_at AT TIME ZONE 'Africa/Nairobi'"

        )

    with op.batch_alter_table('payment_provider_configs', schema=None) as batch_op:
        batch_op.alter_column('last_tested_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,

                postgresql_using="last_tested_at AT TIME ZONE 'Africa/Nairobi'"

        )
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,

                postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'"

        )
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,

                postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'"

        )

    with op.batch_alter_table('payment_method_configs', schema=None) as batch_op:
        batch_op.alter_column('last_tested_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,

                postgresql_using="last_tested_at AT TIME ZONE 'Africa/Nairobi'"

        )

    with op.batch_alter_table('moderation_logs', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,

                postgresql_using="timestamp AT TIME ZONE 'Africa/Nairobi'"

        )

    with op.batch_alter_table('fx_transactions', schema=None) as batch_op:
        batch_op.alter_column('completed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,

                postgresql_using="completed_at AT TIME ZONE 'Africa/Nairobi'"

        )
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,

                postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'"

        )

    with op.batch_alter_table('fx_rates', schema=None) as batch_op:
        batch_op.alter_column('expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,

                postgresql_using="expires_at AT TIME ZONE 'Africa/Nairobi'"

        )
        batch_op.alter_column('timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,

                postgresql_using="timestamp AT TIME ZONE 'Africa/Nairobi'"

        )

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('published_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,

                postgresql_using="published_at AT TIME ZONE 'Africa/Nairobi'"

        )
        batch_op.alter_column('completed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,

                postgresql_using="completed_at AT TIME ZONE 'Africa/Nairobi'"

        )
        batch_op.alter_column('taken_down_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,

                postgresql_using="taken_down_at AT TIME ZONE 'Africa/Nairobi'"

        )
        batch_op.alter_column('deactivated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,

                postgresql_using="deactivated_at AT TIME ZONE 'Africa/Nairobi'"

        )
        batch_op.alter_column('suspended_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,

                postgresql_using="suspended_at AT TIME ZONE 'Africa/Nairobi'"

        )
        batch_op.alter_column('rejected_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,

                postgresql_using="rejected_at AT TIME ZONE 'Africa/Nairobi'"

        )
        batch_op.alter_column('approved_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,

                postgresql_using="approved_at AT TIME ZONE 'Africa/Nairobi'"

        )

    with op.batch_alter_table('event_waitlist', schema=None) as batch_op:
        batch_op.alter_column('converted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,

                postgresql_using="converted_at AT TIME ZONE 'Africa/Nairobi'"

        )
        batch_op.alter_column('notified_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,

                postgresql_using="notified_at AT TIME ZONE 'Africa/Nairobi'"

        )

    with op.batch_alter_table('event_transfer_requests', schema=None) as batch_op:
        batch_op.alter_column('expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,

                postgresql_using="expires_at AT TIME ZONE 'Africa/Nairobi'"

        )
        batch_op.alter_column('approved_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,

                postgresql_using="approved_at AT TIME ZONE 'Africa/Nairobi'"

        )

    with op.batch_alter_table('event_transfer_logs', schema=None) as batch_op:
        batch_op.alter_column('transferred_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,

                postgresql_using="transferred_at AT TIME ZONE 'Africa/Nairobi'"

        )

    with op.batch_alter_table('event_ticket_types', schema=None) as batch_op:
        batch_op.alter_column('available_until',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,

                postgresql_using="available_until AT TIME ZONE 'Africa/Nairobi'"

        )
        batch_op.alter_column('available_from',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,

                postgresql_using="available_from AT TIME ZONE 'Africa/Nairobi'"

        )

    with op.batch_alter_table('event_roles', schema=None) as batch_op:
        batch_op.alter_column('assigned_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,

                postgresql_using="assigned_at AT TIME ZONE 'Africa/Nairobi'"

        )

    with op.batch_alter_table('event_registrations', schema=None) as batch_op:
        batch_op.alter_column('checked_in_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,

                postgresql_using="checked_in_at AT TIME ZONE 'Africa/Nairobi'"

        )

    with op.batch_alter_table('event_host_registrations', schema=None) as batch_op:
        batch_op.alter_column('rejected_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,

                postgresql_using="rejected_at AT TIME ZONE 'Africa/Nairobi'"

        )
        batch_op.alter_column('approved_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,

                postgresql_using="approved_at AT TIME ZONE 'Africa/Nairobi'"

        )
        batch_op.alter_column('registered_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,

                postgresql_using="registered_at AT TIME ZONE 'Africa/Nairobi'"

        )

    with op.batch_alter_table('event_assignments', schema=None) as batch_op:
        batch_op.alter_column('assigned_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,

                postgresql_using="assigned_at AT TIME ZONE 'Africa/Nairobi'"

        )

    with op.batch_alter_table('emergency_access', schema=None) as batch_op:
        batch_op.alter_column('ended_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,

                postgresql_using="ended_at AT TIME ZONE 'Africa/Nairobi'"

        )
        batch_op.alter_column('started_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,

                postgresql_using="started_at AT TIME ZONE 'Africa/Nairobi'"

        )
        batch_op.alter_column('expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,

                postgresql_using="expires_at AT TIME ZONE 'Africa/Nairobi'"

        )

    with op.batch_alter_table('discount_codes', schema=None) as batch_op:
        batch_op.alter_column('valid_until',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,

                postgresql_using="valid_until AT TIME ZONE 'Africa/Nairobi'"

        )
        batch_op.alter_column('valid_from',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,

                postgresql_using="valid_from AT TIME ZONE 'Africa/Nairobi'"

        )

    with op.batch_alter_table('content_submissions', schema=None) as batch_op:
        batch_op.alter_column('sla_due_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,

                postgresql_using="sla_due_at AT TIME ZONE 'Africa/Nairobi'"

        )
        batch_op.alter_column('resolved_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,

                postgresql_using="resolved_at AT TIME ZONE 'Africa/Nairobi'"

        )
        batch_op.alter_column('claimed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,

                postgresql_using="claimed_at AT TIME ZONE 'Africa/Nairobi'"

        )
        batch_op.alter_column('reviewed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,

                postgresql_using="reviewed_at AT TIME ZONE 'Africa/Nairobi'"

        )

    with op.batch_alter_table('content_flags', schema=None) as batch_op:
        batch_op.drop_index('ix_content_flags_risk_score')
        batch_op.create_index(batch_op.f('ix_content_flags_risk_score'), ['risk_score'], unique=False)
        batch_op.alter_column('referred_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,

                postgresql_using="referred_at AT TIME ZONE 'Africa/Nairobi'"

        )
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
                existing_server_default=sa.text('now()'),
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'"

        )


        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
                existing_server_default=sa.text('now()'),
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'"

        )


        batch_op.alter_column('sla_due_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,

                postgresql_using="sla_due_at AT TIME ZONE 'Africa/Nairobi'"

        )
        batch_op.alter_column('resolved_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,

                postgresql_using="resolved_at AT TIME ZONE 'Africa/Nairobi'"

        )

    with op.batch_alter_table('agent_commissions', schema=None) as batch_op:
        batch_op.alter_column('paid_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,

                postgresql_using="paid_at AT TIME ZONE 'Africa/Nairobi'"

        )

    with op.batch_alter_table('agent_commissions', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('content_flags', schema=None) as batch_op:
        batch_op.alter_column('deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('content_submissions', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('discount_codes', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('emergency_access', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('event_assignments', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('event_host_registrations', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('event_moderation_logs', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('event_payment_preferences', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('event_registrations', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('event_roles', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('event_settings', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('event_themes', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('event_ticket_types', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('event_transfer_logs', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('event_transfer_requests', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('event_waitlist', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('moderation_logs', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('payment_method_configs', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('payout_requests', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('wallet_system_configs', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.alter_column('deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('wallet_system_configs', schema=None) as batch_op:
        batch_op.alter_column('deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('payout_requests', schema=None) as batch_op:
        batch_op.alter_column('deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('payment_method_configs', schema=None) as batch_op:
        batch_op.alter_column('deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('moderation_logs', schema=None) as batch_op:
        batch_op.alter_column('deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('event_waitlist', schema=None) as batch_op:
        batch_op.alter_column('deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('event_transfer_requests', schema=None) as batch_op:
        batch_op.alter_column('deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('event_transfer_logs', schema=None) as batch_op:
        batch_op.alter_column('deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('event_ticket_types', schema=None) as batch_op:
        batch_op.alter_column('deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('event_themes', schema=None) as batch_op:
        batch_op.alter_column('deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('event_settings', schema=None) as batch_op:
        batch_op.alter_column('deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('event_roles', schema=None) as batch_op:
        batch_op.alter_column('deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('event_registrations', schema=None) as batch_op:
        batch_op.alter_column('deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('event_payment_preferences', schema=None) as batch_op:
        batch_op.alter_column('deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('event_moderation_logs', schema=None) as batch_op:
        batch_op.alter_column('deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('event_host_registrations', schema=None) as batch_op:
        batch_op.alter_column('deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('event_assignments', schema=None) as batch_op:
        batch_op.alter_column('deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('emergency_access', schema=None) as batch_op:
        batch_op.alter_column('deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('discount_codes', schema=None) as batch_op:
        batch_op.alter_column('deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('content_submissions', schema=None) as batch_op:
        batch_op.alter_column('deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('content_flags', schema=None) as batch_op:
        batch_op.alter_column('deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")

    with op.batch_alter_table('agent_commissions', schema=None) as batch_op:
        batch_op.alter_column('deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               postgresql_using="deleted_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'Africa/Nairobi'")
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'Africa/Nairobi'")

    # ### end Alembic commands ###
