"""add notification tables, preferences, comm settings, aggregators, messages (string enums)

Revision ID: f2f97ca5a313
Revises: 0989dcdb672f
Create Date: 2026-08-05 13:10:45.146177

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f2f97ca5a313'
down_revision = '0989dcdb672f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communication_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('communication_settings', schema=None) as batch_op:
        batch_op.create_index('idx_comm_settings_channel', ['channel'], unique=False)
        batch_op.create_index('idx_comm_settings_key', ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_communication_settings_channel'), ['channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_communication_settings_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_communication_settings_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_communication_settings_key'), ['key'], unique=True)
        batch_op.create_index(batch_op.f('ix_communication_settings_updated_at'), ['updated_at'], unique=False)

    op.create_table('notification_aggregators',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('provider_type', sa.String(length=64), nullable=False),
    sa.Column('channels', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('credentials', sa.JSON(), nullable=True),
    sa.Column('webhook_url', sa.String(length=512), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_aggregators', schema=None) as batch_op:
        batch_op.create_index('idx_agg_enabled', ['enabled'], unique=False)
        batch_op.create_index('idx_agg_provider_type', ['provider_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_aggregators_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_aggregators_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_aggregators_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_notification_aggregators_updated_at'), ['updated_at'], unique=False)

    op.create_table('notification_templates',
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body_template', sa.Text(), nullable=False),
    sa.Column('html_template', sa.Text(), nullable=True),
    sa.Column('default_priority', sa.String(length=16), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_templates_channel'), ['channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_templates_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_templates_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_templates_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_templates_updated_at'), ['updated_at'], unique=False)

    op.create_table('user_notification_preferences',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('notification_type', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_notification_preferences', schema=None) as batch_op:
        batch_op.create_index('idx_unp_user_type_channel', ['user_id', 'notification_type', 'channel'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_notification_preferences_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_notification_preferences_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_notification_preferences_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_notification_preferences_user_id'), ['user_id'], unique=False)

    op.create_table('messages',
    sa.Column('sender_id', sa.BigInteger(), nullable=False),
    sa.Column('recipient_id', sa.BigInteger(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=32), nullable=True),
    sa.Column('direction', sa.String(length=16), nullable=True),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=True),
    sa.Column('notification_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('idx_messages_conversation', ['sender_id', 'recipient_id'], unique=False)
        batch_op.create_index('idx_messages_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_messages_recipient', ['recipient_id'], unique=False)
        batch_op.create_index('idx_messages_sender', ['sender_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_recipient_id'), ['recipient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_sender_id'), ['sender_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_updated_at'), ['updated_at'], unique=False)

    op.create_table('notification_logs',
    sa.Column('notification_id', sa.BigInteger(), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('response_code', sa.BigInteger(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_logs_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_logs_notification_id'), ['notification_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_logs_updated_at'), ['updated_at'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('channel', sa.String(length=16), server_default='in_app', nullable=False))
        batch_op.add_column(sa.Column('template_id', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('context', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('subject', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('body', sa.Text(), nullable=False, server_default=sa.text("''")))
        batch_op.add_column(sa.Column('scheduled_for', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('attempts', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('last_error', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('external_id', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('parent_id', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('dead_letter', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_attempt_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('type',
               existing_type=postgresql.ENUM('PROPERTY_SUBMITTED', 'PROPERTY_APPROVED', 'PROPERTY_REJECTED', 'PROPERTY_CHANGES_REQUESTED', 'PROPERTY_SUSPENDED', 'PROPERTY_REINSTATED', 'BOOKING_CONFIRMED', 'BOOKING_CANCELLED', 'REVIEW_RECEIVED', 'VERIFICATION_EMAIL', 'PASSWORD_RESET', 'LOGIN_ALERT', 'BOOKING_UPDATE', 'DRIVER_ASSIGNED', 'EVENT_REGISTERED', 'EVENT_REMINDER', 'DEPOSIT_CONFIRMED', 'WITHDRAWAL_COMPLETED', 'TRANSACTION_COMPLETED', 'PAYMENT_RECEIVED', name='notificationtype'),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('priority',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=16),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=16),
               existing_nullable=True)
        batch_op.alter_column('link',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=512),
               existing_nullable=True)
        batch_op.create_index('idx_notifications_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(None, 'notification_templates', ['template_id'], ['id'])
        batch_op.create_foreign_key(None, 'notifications', ['parent_id'], ['id'])
        batch_op.drop_column('channels')
        batch_op.drop_column('data')
        batch_op.drop_column('title')
        batch_op.drop_column('message')

    # Normalize historical uppercase enum labels to the lowercase values used by the
    # application, then enforce allowed values with CHECK constraints (replaces native ENUMs).
    op.execute("UPDATE notifications SET type = lower(type::text) WHERE type IS NOT NULL")
    op.execute("UPDATE notifications SET status = lower(status::text) WHERE status IS NOT NULL")
    op.create_check_constraint(
        'ck_notifications_status',
        'notifications',
        "status IN ('pending','sent','delivered','failed','read','cancelled')",
    )
    op.create_check_constraint(
        'ck_notifications_channel',
        'notifications',
        "channel IN ('in_app','email','sms','push','webhook')",
    )
    op.create_check_constraint(
        'ck_notifications_type',
        'notifications',
        "type IN ("
        "'property_submitted','property_approved','property_rejected',"
        "'property_changes_requested','property_suspended','property_reinstated',"
        "'property_archived','property_restored','booking_confirmed','booking_cancelled',"
        "'review_received','verification_email','password_reset','login_alert',"
        "'booking_update','driver_assigned','event_registered','event_reminder',"
        "'deposit_confirmed','withdrawal_completed','transaction_completed','payment_received',"
        "'system_alert','platform_announcement','internal_message','internal_reply',"
        "'admin_notification','signup_notification','transaction_notification','message_notification'"
        ")",
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('channels', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_type'))
        batch_op.drop_index(batch_op.f('ix_notifications_external_id'))
        batch_op.drop_index('idx_notifications_status')
        batch_op.alter_column('link',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('priority',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('PROPERTY_SUBMITTED', 'PROPERTY_APPROVED', 'PROPERTY_REJECTED', 'PROPERTY_CHANGES_REQUESTED', 'PROPERTY_SUSPENDED', 'PROPERTY_REINSTATED', 'BOOKING_CONFIRMED', 'BOOKING_CANCELLED', 'REVIEW_RECEIVED', 'VERIFICATION_EMAIL', 'PASSWORD_RESET', 'LOGIN_ALERT', 'BOOKING_UPDATE', 'DRIVER_ASSIGNED', 'EVENT_REGISTERED', 'EVENT_REMINDER', 'DEPOSIT_CONFIRMED', 'WITHDRAWAL_COMPLETED', 'TRANSACTION_COMPLETED', 'PAYMENT_RECEIVED', name='notificationtype'),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.drop_column('last_attempt_at')
        batch_op.drop_column('dead_letter')
        batch_op.drop_column('parent_id')
        batch_op.drop_column('external_id')
        batch_op.drop_column('last_error')
        batch_op.drop_column('attempts')
        batch_op.drop_column('scheduled_for')
        batch_op.drop_column('body')
        batch_op.drop_column('subject')
        batch_op.drop_column('context')
        batch_op.drop_column('template_id')
        batch_op.drop_column('channel')
        batch_op.drop_column('phone')
        batch_op.drop_column('email')

    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_logs_updated_at'))
        batch_op.drop_index(batch_op.f('ix_notification_logs_notification_id'))
        batch_op.drop_index(batch_op.f('ix_notification_logs_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_notification_logs_created_at'))

    op.drop_table('notification_logs')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_updated_at'))
        batch_op.drop_index(batch_op.f('ix_messages_sender_id'))
        batch_op.drop_index(batch_op.f('ix_messages_recipient_id'))
        batch_op.drop_index(batch_op.f('ix_messages_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_messages_created_at'))
        batch_op.drop_index('idx_messages_sender')
        batch_op.drop_index('idx_messages_recipient')
        batch_op.drop_index('idx_messages_created_at')
        batch_op.drop_index('idx_messages_conversation')

    op.drop_table('messages')
    with op.batch_alter_table('user_notification_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_notification_preferences_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_notification_preferences_updated_at'))
        batch_op.drop_index(batch_op.f('ix_user_notification_preferences_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_user_notification_preferences_created_at'))
        batch_op.drop_index('idx_unp_user_type_channel')

    op.drop_table('user_notification_preferences')
    with op.batch_alter_table('notification_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_templates_updated_at'))
        batch_op.drop_index(batch_op.f('ix_notification_templates_type'))
        batch_op.drop_index(batch_op.f('ix_notification_templates_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_notification_templates_created_at'))
        batch_op.drop_index(batch_op.f('ix_notification_templates_channel'))

    op.drop_table('notification_templates')
    with op.batch_alter_table('notification_aggregators', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_aggregators_updated_at'))
        batch_op.drop_index(batch_op.f('ix_notification_aggregators_name'))
        batch_op.drop_index(batch_op.f('ix_notification_aggregators_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_notification_aggregators_created_at'))
        batch_op.drop_index('idx_agg_provider_type')
        batch_op.drop_index('idx_agg_enabled')

    op.drop_table('notification_aggregators')
    with op.batch_alter_table('communication_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_communication_settings_updated_at'))
        batch_op.drop_index(batch_op.f('ix_communication_settings_key'))
        batch_op.drop_index(batch_op.f('ix_communication_settings_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_communication_settings_created_at'))
        batch_op.drop_index(batch_op.f('ix_communication_settings_channel'))
        batch_op.drop_index('idx_comm_settings_key')
        batch_op.drop_index('idx_comm_settings_channel')

    op.drop_table('communication_settings')
    # ### end Alembic commands ###
