"""create accommodation_booking_payments table

Revision ID: f312046d12e8
Revises: 978f0c336ca4
Create Date: 2026-07-31 10:45:32.131101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f312046d12e8'
down_revision = '978f0c336ca4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accommodation_booking_payments',
    sa.Column('booking_id', sa.BigInteger(), nullable=False),
    sa.Column('wallet_txn_id', sa.String(length=255), nullable=True),
    sa.Column('payment_reference', sa.String(length=50), nullable=False),
    sa.Column('payment_status', sa.String(length=30), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('payment_gateway', sa.String(length=50), nullable=True),
    sa.Column('gateway_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['accommodation_bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id', 'payment_reference', name='uq_ac_booking_payment_ref')
    )
    with op.batch_alter_table('accommodation_booking_payments', schema=None) as batch_op:
        batch_op.create_index('idx_ac_book_payment_booking', ['booking_id', 'payment_status'], unique=False)
        batch_op.create_index('idx_ac_book_payment_reference', ['payment_reference'], unique=True)
        batch_op.create_index('idx_ac_book_payment_wallet_txn', ['wallet_txn_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_booking_payments_booking_id'), ['booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_booking_payments_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_accommodation_booking_payments_payment_reference'), ['payment_reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_accommodation_booking_payments_wallet_txn_id'), ['wallet_txn_id'], unique=False)

    with op.batch_alter_table('aggregators', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aggregators_api_key'))
        batch_op.create_index('ix_aggregators_api_key', ['api_key'], unique=False)

    with op.batch_alter_table('content_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_flags_risk_score'))
        batch_op.create_index('ix_content_flags_risk_score', ['risk_score', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_flags', schema=None) as batch_op:
        batch_op.drop_index('ix_content_flags_risk_score')
        batch_op.create_index(batch_op.f('ix_content_flags_risk_score'), ['risk_score'], unique=False)

    with op.batch_alter_table('aggregators', schema=None) as batch_op:
        batch_op.drop_index('ix_aggregators_api_key')
        batch_op.create_index(batch_op.f('ix_aggregators_api_key'), ['api_key'], unique=True)

    with op.batch_alter_table('accommodation_booking_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accommodation_booking_payments_wallet_txn_id'))
        batch_op.drop_index(batch_op.f('ix_accommodation_booking_payments_payment_reference'))
        batch_op.drop_index(batch_op.f('ix_accommodation_booking_payments_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_accommodation_booking_payments_booking_id'))
        batch_op.drop_index('idx_ac_book_payment_wallet_txn')
        batch_op.drop_index('idx_ac_book_payment_reference')
        batch_op.drop_index('idx_ac_book_payment_booking')

    op.drop_table('accommodation_booking_payments')
    # ### end Alembic commands ###
