"""Add SystemConfiguration model for system-wide settings

Revision ID: f898e8aae452
Revises: 723b9cea8d97
Create Date: 2026-05-06 17:40:57.895412

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f898e8aae452'
down_revision = '723b9cea8d97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_configurations',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('value_type', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_configurations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_configurations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_configurations_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_configurations_key'), ['key'], unique=True)
        batch_op.create_index(batch_op.f('ix_system_configurations_updated_at'), ['updated_at'], unique=False)

    with op.batch_alter_table('content_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_flags_compliance_case_id'))
        batch_op.drop_index(batch_op.f('ix_content_flags_created_at'))
        batch_op.drop_index(batch_op.f('ix_content_flags_entity_id'))
        batch_op.drop_index(batch_op.f('ix_content_flags_entity_type'))
        batch_op.drop_index(batch_op.f('ix_content_flags_flagged_by'))
        batch_op.drop_index(batch_op.f('ix_content_flags_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_content_flags_priority'))
        batch_op.drop_index(batch_op.f('ix_content_flags_referred_to_compliance'))
        batch_op.drop_index(batch_op.f('ix_content_flags_status'))
        batch_op.drop_index(batch_op.f('ix_content_flags_updated_at'))
        batch_op.drop_index(batch_op.f('ix_flags_entity'))
        batch_op.drop_index(batch_op.f('ix_flags_status_priority'))

    op.drop_table('content_flags')
    with op.batch_alter_table('data_change_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_dc_public_id'))
        batch_op.create_index('idx_dc_public_id', ['public_id'], unique=False)
        batch_op.create_unique_constraint(None, ['public_id'])

    with op.batch_alter_table('emergency_access', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_emergency_access_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_emergency_access_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_emergency_access_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_emergency_access_updated_at'), ['updated_at'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_emergency_access_expires'))
        batch_op.drop_index(batch_op.f('ix_users_emergency_access_granted'))
        batch_op.drop_constraint(batch_op.f('fk_users_emergency_access_granted_by'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['emergency_access_granted_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_users_emergency_access_granted_by'), 'users', ['emergency_access_granted_by'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('ix_users_emergency_access_granted'), ['emergency_access_granted'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_emergency_access_expires'), ['emergency_access_expires'], unique=False)

    with op.batch_alter_table('emergency_access', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emergency_access_updated_at'))
        batch_op.drop_index(batch_op.f('ix_emergency_access_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_emergency_access_is_active'))
        batch_op.drop_index(batch_op.f('ix_emergency_access_created_at'))
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('data_change_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index('idx_dc_public_id')
        batch_op.create_index(batch_op.f('idx_dc_public_id'), ['public_id'], unique=True)

    op.create_table('content_flags',
    sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('flagged_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('priority', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('escalated_to_role', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('assigned_to', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('resolved_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('resolution_action', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('resolution_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('resolved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('sla_due_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('compliance_case_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('referred_to_compliance', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('referred_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('referred_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name=op.f('content_flags_assigned_to_fkey')),
    sa.ForeignKeyConstraint(['compliance_case_id'], ['compliance_cases.id'], name=op.f('content_flags_compliance_case_id_fkey')),
    sa.ForeignKeyConstraint(['flagged_by'], ['users.id'], name=op.f('content_flags_flagged_by_fkey')),
    sa.ForeignKeyConstraint(['referred_by'], ['users.id'], name=op.f('content_flags_referred_by_fkey')),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], name=op.f('content_flags_resolved_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('content_flags_pkey'))
    )
    with op.batch_alter_table('content_flags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flags_status_priority'), ['status', 'priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_flags_entity'), ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_flags_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_flags_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_flags_referred_to_compliance'), ['referred_to_compliance'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_flags_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_flags_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_flags_flagged_by'), ['flagged_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_flags_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_flags_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_flags_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_flags_compliance_case_id'), ['compliance_case_id'], unique=False)

    with op.batch_alter_table('system_configurations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_configurations_updated_at'))
        batch_op.drop_index(batch_op.f('ix_system_configurations_key'))
        batch_op.drop_index(batch_op.f('ix_system_configurations_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_system_configurations_created_at'))

    op.drop_table('system_configurations')
    # ### end Alembic commands ###
