"""add backup_records table

Revision ID: fc0f4f135025
Revises: 20260811_1125
Create Date: 2026-08-11 15:57:14.609221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc0f4f135025'
down_revision = '20260811_1125'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_records',
    sa.Column('public_id', sa.String(length=64), nullable=False),
    sa.Column('backup_type', sa.String(length=20), nullable=False),
    sa.Column('backup_schedule', sa.String(length=20), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backup_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backup_records_backup_type'), ['backup_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_backup_records_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_backup_records_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_backup_records_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_backup_records_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_backup_records_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backup_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backup_records_updated_at'))
        batch_op.drop_index(batch_op.f('ix_backup_records_status'))
        batch_op.drop_index(batch_op.f('ix_backup_records_public_id'))
        batch_op.drop_index(batch_op.f('ix_backup_records_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_backup_records_created_at'))
        batch_op.drop_index(batch_op.f('ix_backup_records_backup_type'))

    op.drop_table('backup_records')
    # ### end Alembic commands ###
