"""
sync managed check constraints

Generated by:
scripts/sync_check_constraints.py

Environment: development

Revision ID: 1787899767
Revises: 20260828_booking_mode_default
Create Date: 2026-08-28 09:49:27

Source of truth:
    SQLAlchemy model metadata

Target:
    Live PostgreSQL database
"""

from alembic import op


revision = '1787899767'
down_revision = '20260828_booking_mode_default'
branch_labels = None
depends_on = None


def upgrade():
    op.drop_constraint('ck_notifications_type', 'notifications', type_='check')
    op.create_check_constraint('ck_notifications_type', 'notifications', "type IN ('property_submitted','property_approved','property_rejected','property_changes_requested','property_suspended','property_reinstated','property_archived','property_restored','booking_confirmed','booking_pending','third_party_booking','booking_cancelled','booking_pending_approval','booking_approved','booking_rejected','booking_payment_received_pending_approval','review_received','accommodation_complaint_opened','booking_expired','booking_no_show','event_accommodation_assigned','event_accommodation_cancelled','verification_email','password_reset','login_alert','booking_update','driver_assigned','event_registered','event_reminder','event_staff_added','event_staff_removed','event_staff_updated','deposit_confirmed','withdrawal_completed','transaction_completed','payment_received','system_alert','platform_announcement','internal_message','internal_reply','admin_notification','signup_notification','transaction_notification','message_notification','compliance_case_created','compliance_case_assigned','compliance_case_updated','compliance_case_escalated','compliance_case_resolved')")


def downgrade():
    op.drop_constraint('ck_notifications_type', 'notifications', type_='check')
    op.create_check_constraint('ck_notifications_type', 'notifications', "type::text = ANY (ARRAY['property_submitted'::character varying, 'property_approved'::character varying, 'property_rejected'::character varying, 'property_changes_requested'::character varying, 'property_suspended'::character varying, 'property_reinstated'::character varying, 'property_archived'::character varying, 'property_restored'::character varying, 'booking_confirmed'::character varying, 'booking_pending'::character varying, 'third_party_booking'::character varying, 'booking_cancelled'::character varying, 'review_received'::character varying, 'accommodation_complaint_opened'::character varying, 'booking_expired'::character varying, 'booking_no_show'::character varying, 'event_accommodation_assigned'::character varying, 'event_accommodation_cancelled'::character varying, 'verification_email'::character varying, 'password_reset'::character varying, 'login_alert'::character varying, 'booking_update'::character varying, 'driver_assigned'::character varying, 'event_registered'::character varying, 'event_reminder'::character varying, 'event_staff_added'::character varying, 'event_staff_removed'::character varying, 'event_staff_updated'::character varying, 'deposit_confirmed'::character varying, 'withdrawal_completed'::character varying, 'transaction_completed'::character varying, 'payment_received'::character varying, 'system_alert'::character varying, 'platform_announcement'::character varying, 'internal_message'::character varying, 'internal_reply'::character varying, 'admin_notification'::character varying, 'signup_notification'::character varying, 'transaction_notification'::character varying, 'message_notification'::character varying, 'compliance_case_created'::character varying, 'compliance_case_assigned'::character varying, 'compliance_case_updated'::character varying, 'compliance_case_escalated'::character varying, 'compliance_case_resolved'::character varying]::text[])")
