"""drop redundant organizer_profiles status index

Revision ID: 91911883eb58
Revises: 23a2748dc5d1
Create Date: 2026-08-21 15:44:51.371958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91911883eb58'
down_revision = '23a2748dc5d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizer_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_organizer_profile_status'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizer_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_organizer_profile_status'), ['status'], unique=False)

    # ### end Alembic commands ###
